#ifndef _PEANO_APPLICATIONS_HEATEQUATION_TIMESTEPPING_RECORDS_SPACETREEGRIDSTATE_H
#define _PEANO_APPLICATIONS_HEATEQUATION_TIMESTEPPING_RECORDS_SPACETREEGRIDSTATE_H

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>
#include "peano/utils/Globals.h"

namespace peano {
   namespace applications {
      namespace heatequation {
         namespace timestepping {
            namespace records {
               class SpacetreeGridState;
               class SpacetreeGridStatePacked;
            }
         }
      }
   }
}

#if defined(Parallel)
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 09-12-2010 17:47
    *
    * @date   28/06/2011 13:55
    */
   class peano::applications::heatequation::timestepping::records::SpacetreeGridState { 
      
      public:
         
         typedef peano::applications::heatequation::timestepping::records::SpacetreeGridStatePacked Packed;
         
         struct PersistentRecords {
            double _omega;
            double _updateUMax;
            double _updateUH;
            double _uMax;
            double _uH;
            double _uGlobalMax;
            double _uGlobalH;
            int _timeStep;
            double _timeStepSize;
            double _time;
            double _numberOfStencilUpdates;
            double _minimalAllowedMeshSize;
            double _maximalAllowedMeshSize;
            int _activeLevel;
            tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
            tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
            double _numberOfInnerVertices;
            double _numberOfBoundaryVertices;
            double _numberOfOuterVertices;
            double _numberOfInnerCells;
            double _numberOfOuterCells;
            int _maxLevel;
            bool _hasRefined;
            bool _hasTriggeredRefinementForNextIteration;
            bool _hasErased;
            bool _hasTriggeredEraseForNextIteration;
            bool _hasChangedVertexOrCellState;
            bool _isTraversalInverted;
            bool _deriveAdjacencyInformation;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
            
            /**
             * Generated
             */
            double getOmega() const;
            
            /**
             * Generated
             */
            void setOmega(const double& omega);
            
            /**
             * Generated
             */
            double getUpdateUMax() const;
            
            /**
             * Generated
             */
            void setUpdateUMax(const double& updateUMax);
            
            /**
             * Generated
             */
            double getUpdateUH() const;
            
            /**
             * Generated
             */
            void setUpdateUH(const double& updateUH);
            
            /**
             * Generated
             */
            double getUMax() const;
            
            /**
             * Generated
             */
            void setUMax(const double& uMax);
            
            /**
             * Generated
             */
            double getUH() const;
            
            /**
             * Generated
             */
            void setUH(const double& uH);
            
            /**
             * Generated
             */
            double getUGlobalMax() const;
            
            /**
             * Generated
             */
            void setUGlobalMax(const double& uGlobalMax);
            
            /**
             * Generated
             */
            double getUGlobalH() const;
            
            /**
             * Generated
             */
            void setUGlobalH(const double& uGlobalH);
            
            /**
             * Generated
             */
            int getTimeStep() const;
            
            /**
             * Generated
             */
            void setTimeStep(const int& timeStep);
            
            /**
             * Generated
             */
            double getTimeStepSize() const;
            
            /**
             * Generated
             */
            void setTimeStepSize(const double& timeStepSize);
            
            /**
             * Generated
             */
            double getTime() const;
            
            /**
             * Generated
             */
            void setTime(const double& time);
            
            /**
             * Generated
             */
            double getNumberOfStencilUpdates() const;
            
            /**
             * Generated
             */
            void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
            
            /**
             * Generated
             */
            double getMinimalAllowedMeshSize() const;
            
            /**
             * Generated
             */
            void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
            
            /**
             * Generated
             */
            double getMaximalAllowedMeshSize() const;
            
            /**
             * Generated
             */
            void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
            
            /**
             * Generated
             */
            int getActiveLevel() const;
            
            /**
             * Generated
             */
            void setActiveLevel(const int& activeLevel);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
            
            /**
             * Generated
             */
            void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
            
            /**
             * Generated
             */
            void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
            
            /**
             * Generated
             */
            double getNumberOfInnerVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerVertices(const double& numberOfInnerVertices);
            
            /**
             * Generated
             */
            double getNumberOfBoundaryVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
            
            /**
             * Generated
             */
            double getNumberOfOuterVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterVertices(const double& numberOfOuterVertices);
            
            /**
             * Generated
             */
            double getNumberOfInnerCells() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerCells(const double& numberOfInnerCells);
            
            /**
             * Generated
             */
            double getNumberOfOuterCells() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterCells(const double& numberOfOuterCells);
            
            /**
             * Generated
             */
            int getMaxLevel() const;
            
            /**
             * Generated
             */
            void setMaxLevel(const int& maxLevel);
            
            /**
             * Generated
             */
            bool getHasRefined() const;
            
            /**
             * Generated
             */
            void setHasRefined(const bool& hasRefined);
            
            /**
             * Generated
             */
            bool getHasTriggeredRefinementForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
            
            /**
             * Generated
             */
            bool getHasErased() const;
            
            /**
             * Generated
             */
            void setHasErased(const bool& hasErased);
            
            /**
             * Generated
             */
            bool getHasTriggeredEraseForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
            
            /**
             * Generated
             */
            bool getHasChangedVertexOrCellState() const;
            
            /**
             * Generated
             */
            void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
            
            /**
             * Generated
             */
            bool getIsTraversalInverted() const;
            
            /**
             * Generated
             */
            void setIsTraversalInverted(const bool& isTraversalInverted);
            
            /**
             * Generated
             */
            bool getDeriveAdjacencyInformation() const;
            
            /**
             * Generated
             */
            void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         SpacetreeGridState();
         
         /**
          * Generated
          */
         SpacetreeGridState(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         SpacetreeGridState(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
         
         /**
          * Generated
          */
         virtual ~SpacetreeGridState();
         
         /**
          * Generated
          */
         double getOmega() const;
         
         /**
          * Generated
          */
         void setOmega(const double& omega);
         
         /**
          * Generated
          */
         double getUpdateUMax() const;
         
         /**
          * Generated
          */
         void setUpdateUMax(const double& updateUMax);
         
         /**
          * Generated
          */
         double getUpdateUH() const;
         
         /**
          * Generated
          */
         void setUpdateUH(const double& updateUH);
         
         /**
          * Generated
          */
         double getUMax() const;
         
         /**
          * Generated
          */
         void setUMax(const double& uMax);
         
         /**
          * Generated
          */
         double getUH() const;
         
         /**
          * Generated
          */
         void setUH(const double& uH);
         
         /**
          * Generated
          */
         double getUGlobalMax() const;
         
         /**
          * Generated
          */
         void setUGlobalMax(const double& uGlobalMax);
         
         /**
          * Generated
          */
         double getUGlobalH() const;
         
         /**
          * Generated
          */
         void setUGlobalH(const double& uGlobalH);
         
         /**
          * Generated
          */
         int getTimeStep() const;
         
         /**
          * Generated
          */
         void setTimeStep(const int& timeStep);
         
         /**
          * Generated
          */
         double getTimeStepSize() const;
         
         /**
          * Generated
          */
         void setTimeStepSize(const double& timeStepSize);
         
         /**
          * Generated
          */
         double getTime() const;
         
         /**
          * Generated
          */
         void setTime(const double& time);
         
         /**
          * Generated
          */
         double getNumberOfStencilUpdates() const;
         
         /**
          * Generated
          */
         void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
         
         /**
          * Generated
          */
         double getMinimalAllowedMeshSize() const;
         
         /**
          * Generated
          */
         void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
         
         /**
          * Generated
          */
         double getMaximalAllowedMeshSize() const;
         
         /**
          * Generated
          */
         void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
         
         /**
          * Generated
          */
         int getActiveLevel() const;
         
         /**
          * Generated
          */
         void setActiveLevel(const int& activeLevel);
         
         /**
          * Generated
          */
         tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
         
         /**
          * Generated
          */
         void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
         
         /**
          * Generated
          */
         double getMinMeshWidth(int elementIndex) const;
         
         /**
          * Generated
          */
         void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
         
         /**
          * Generated
          */
         tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
         
         /**
          * Generated
          */
         void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
         
         /**
          * Generated
          */
         double getMaxMeshWidth(int elementIndex) const;
         
         /**
          * Generated
          */
         void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
         
         /**
          * Generated
          */
         double getNumberOfInnerVertices() const;
         
         /**
          * Generated
          */
         void setNumberOfInnerVertices(const double& numberOfInnerVertices);
         
         /**
          * Generated
          */
         double getNumberOfBoundaryVertices() const;
         
         /**
          * Generated
          */
         void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
         
         /**
          * Generated
          */
         double getNumberOfOuterVertices() const;
         
         /**
          * Generated
          */
         void setNumberOfOuterVertices(const double& numberOfOuterVertices);
         
         /**
          * Generated
          */
         double getNumberOfInnerCells() const;
         
         /**
          * Generated
          */
         void setNumberOfInnerCells(const double& numberOfInnerCells);
         
         /**
          * Generated
          */
         double getNumberOfOuterCells() const;
         
         /**
          * Generated
          */
         void setNumberOfOuterCells(const double& numberOfOuterCells);
         
         /**
          * Generated
          */
         int getMaxLevel() const;
         
         /**
          * Generated
          */
         void setMaxLevel(const int& maxLevel);
         
         /**
          * Generated
          */
         bool getHasRefined() const;
         
         /**
          * Generated
          */
         void setHasRefined(const bool& hasRefined);
         
         /**
          * Generated
          */
         bool getHasTriggeredRefinementForNextIteration() const;
         
         /**
          * Generated
          */
         void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
         
         /**
          * Generated
          */
         bool getHasErased() const;
         
         /**
          * Generated
          */
         void setHasErased(const bool& hasErased);
         
         /**
          * Generated
          */
         bool getHasTriggeredEraseForNextIteration() const;
         
         /**
          * Generated
          */
         void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
         
         /**
          * Generated
          */
         bool getHasChangedVertexOrCellState() const;
         
         /**
          * Generated
          */
         void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
         
         /**
          * Generated
          */
         bool getIsTraversalInverted() const;
         
         /**
          * Generated
          */
         void setIsTraversalInverted(const bool& isTraversalInverted);
         
         /**
          * Generated
          */
         bool getDeriveAdjacencyInformation() const;
         
         /**
          * Generated
          */
         void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         SpacetreeGridStatePacked convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      /**
       * @author This class was autogenerated by DaStGen
       * 		   DataStructureGenerator (DaStGen), 2007-2009,
       * 		   by Wolfgang Eckhardt
       *
       * 		   build date: 09-12-2010 17:47
       *
       * @date   28/06/2011 13:55
       */
      class peano::applications::heatequation::timestepping::records::SpacetreeGridStatePacked { 
         
         public:
            
            struct PersistentRecords {
               double _omega;
               double _updateUMax;
               double _updateUH;
               double _uMax;
               double _uH;
               double _uGlobalMax;
               double _uGlobalH;
               int _timeStep;
               double _timeStepSize;
               double _time;
               double _numberOfStencilUpdates;
               double _minimalAllowedMeshSize;
               double _maximalAllowedMeshSize;
               int _activeLevel;
               tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
               tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
               double _numberOfInnerVertices;
               double _numberOfBoundaryVertices;
               double _numberOfOuterVertices;
               double _numberOfInnerCells;
               double _numberOfOuterCells;
               int _maxLevel;
               bool _isTraversalInverted;
               bool _deriveAdjacencyInformation;
               
               /** mapping of records:
               || Member 	|| startbit 	|| length
                |  hasRefined	| startbit 0	| #bits 1
                |  hasTriggeredRefinementForNextIteration	| startbit 1	| #bits 1
                |  hasErased	| startbit 2	| #bits 1
                |  hasTriggeredEraseForNextIteration	| startbit 3	| #bits 1
                |  hasChangedVertexOrCellState	| startbit 4	| #bits 1
                */
               short int _packedRecords0;
               
               /**
                * Generated
                */
               PersistentRecords();
               
               /**
                * Generated
                */
               PersistentRecords(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
               
               /**
                * Generated
                */
               double getOmega() const;
               
               /**
                * Generated
                */
               void setOmega(const double& omega);
               
               /**
                * Generated
                */
               double getUpdateUMax() const;
               
               /**
                * Generated
                */
               void setUpdateUMax(const double& updateUMax);
               
               /**
                * Generated
                */
               double getUpdateUH() const;
               
               /**
                * Generated
                */
               void setUpdateUH(const double& updateUH);
               
               /**
                * Generated
                */
               double getUMax() const;
               
               /**
                * Generated
                */
               void setUMax(const double& uMax);
               
               /**
                * Generated
                */
               double getUH() const;
               
               /**
                * Generated
                */
               void setUH(const double& uH);
               
               /**
                * Generated
                */
               double getUGlobalMax() const;
               
               /**
                * Generated
                */
               void setUGlobalMax(const double& uGlobalMax);
               
               /**
                * Generated
                */
               double getUGlobalH() const;
               
               /**
                * Generated
                */
               void setUGlobalH(const double& uGlobalH);
               
               /**
                * Generated
                */
               int getTimeStep() const;
               
               /**
                * Generated
                */
               void setTimeStep(const int& timeStep);
               
               /**
                * Generated
                */
               double getTimeStepSize() const;
               
               /**
                * Generated
                */
               void setTimeStepSize(const double& timeStepSize);
               
               /**
                * Generated
                */
               double getTime() const;
               
               /**
                * Generated
                */
               void setTime(const double& time);
               
               /**
                * Generated
                */
               double getNumberOfStencilUpdates() const;
               
               /**
                * Generated
                */
               void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
               
               /**
                * Generated
                */
               double getMinimalAllowedMeshSize() const;
               
               /**
                * Generated
                */
               void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
               
               /**
                * Generated
                */
               double getMaximalAllowedMeshSize() const;
               
               /**
                * Generated
                */
               void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
               
               /**
                * Generated
                */
               int getActiveLevel() const;
               
               /**
                * Generated
                */
               void setActiveLevel(const int& activeLevel);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
               
               /**
                * Generated
                */
               void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
               
               /**
                * Generated
                */
               void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
               
               /**
                * Generated
                */
               double getNumberOfInnerVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerVertices(const double& numberOfInnerVertices);
               
               /**
                * Generated
                */
               double getNumberOfBoundaryVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
               
               /**
                * Generated
                */
               double getNumberOfOuterVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterVertices(const double& numberOfOuterVertices);
               
               /**
                * Generated
                */
               double getNumberOfInnerCells() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerCells(const double& numberOfInnerCells);
               
               /**
                * Generated
                */
               double getNumberOfOuterCells() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterCells(const double& numberOfOuterCells);
               
               /**
                * Generated
                */
               int getMaxLevel() const;
               
               /**
                * Generated
                */
               void setMaxLevel(const int& maxLevel);
               
               /**
                * Generated
                */
               bool getHasRefined() const;
               
               /**
                * Generated
                */
               void setHasRefined(const bool& hasRefined);
               
               /**
                * Generated
                */
               bool getHasTriggeredRefinementForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
               
               /**
                * Generated
                */
               bool getHasErased() const;
               
               /**
                * Generated
                */
               void setHasErased(const bool& hasErased);
               
               /**
                * Generated
                */
               bool getHasTriggeredEraseForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
               
               /**
                * Generated
                */
               bool getHasChangedVertexOrCellState() const;
               
               /**
                * Generated
                */
               void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
               
               /**
                * Generated
                */
               bool getIsTraversalInverted() const;
               
               /**
                * Generated
                */
               void setIsTraversalInverted(const bool& isTraversalInverted);
               
               /**
                * Generated
                */
               bool getDeriveAdjacencyInformation() const;
               
               /**
                * Generated
                */
               void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
               
               
            };
            
         private: 
            PersistentRecords _persistentRecords;
            
         public:
            /**
             * Generated
             */
            SpacetreeGridStatePacked();
            
            /**
             * Generated
             */
            SpacetreeGridStatePacked(const PersistentRecords& persistentRecords);
            
            /**
             * Generated
             */
            SpacetreeGridStatePacked(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
            
            /**
             * Generated
             */
            virtual ~SpacetreeGridStatePacked();
            
            /**
             * Generated
             */
            double getOmega() const;
            
            /**
             * Generated
             */
            void setOmega(const double& omega);
            
            /**
             * Generated
             */
            double getUpdateUMax() const;
            
            /**
             * Generated
             */
            void setUpdateUMax(const double& updateUMax);
            
            /**
             * Generated
             */
            double getUpdateUH() const;
            
            /**
             * Generated
             */
            void setUpdateUH(const double& updateUH);
            
            /**
             * Generated
             */
            double getUMax() const;
            
            /**
             * Generated
             */
            void setUMax(const double& uMax);
            
            /**
             * Generated
             */
            double getUH() const;
            
            /**
             * Generated
             */
            void setUH(const double& uH);
            
            /**
             * Generated
             */
            double getUGlobalMax() const;
            
            /**
             * Generated
             */
            void setUGlobalMax(const double& uGlobalMax);
            
            /**
             * Generated
             */
            double getUGlobalH() const;
            
            /**
             * Generated
             */
            void setUGlobalH(const double& uGlobalH);
            
            /**
             * Generated
             */
            int getTimeStep() const;
            
            /**
             * Generated
             */
            void setTimeStep(const int& timeStep);
            
            /**
             * Generated
             */
            double getTimeStepSize() const;
            
            /**
             * Generated
             */
            void setTimeStepSize(const double& timeStepSize);
            
            /**
             * Generated
             */
            double getTime() const;
            
            /**
             * Generated
             */
            void setTime(const double& time);
            
            /**
             * Generated
             */
            double getNumberOfStencilUpdates() const;
            
            /**
             * Generated
             */
            void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
            
            /**
             * Generated
             */
            double getMinimalAllowedMeshSize() const;
            
            /**
             * Generated
             */
            void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
            
            /**
             * Generated
             */
            double getMaximalAllowedMeshSize() const;
            
            /**
             * Generated
             */
            void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
            
            /**
             * Generated
             */
            int getActiveLevel() const;
            
            /**
             * Generated
             */
            void setActiveLevel(const int& activeLevel);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
            
            /**
             * Generated
             */
            void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
            
            /**
             * Generated
             */
            double getMinMeshWidth(int elementIndex) const;
            
            /**
             * Generated
             */
            void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
            
            /**
             * Generated
             */
            void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
            
            /**
             * Generated
             */
            double getMaxMeshWidth(int elementIndex) const;
            
            /**
             * Generated
             */
            void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
            
            /**
             * Generated
             */
            double getNumberOfInnerVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerVertices(const double& numberOfInnerVertices);
            
            /**
             * Generated
             */
            double getNumberOfBoundaryVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
            
            /**
             * Generated
             */
            double getNumberOfOuterVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterVertices(const double& numberOfOuterVertices);
            
            /**
             * Generated
             */
            double getNumberOfInnerCells() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerCells(const double& numberOfInnerCells);
            
            /**
             * Generated
             */
            double getNumberOfOuterCells() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterCells(const double& numberOfOuterCells);
            
            /**
             * Generated
             */
            int getMaxLevel() const;
            
            /**
             * Generated
             */
            void setMaxLevel(const int& maxLevel);
            
            /**
             * Generated
             */
            bool getHasRefined() const;
            
            /**
             * Generated
             */
            void setHasRefined(const bool& hasRefined);
            
            /**
             * Generated
             */
            bool getHasTriggeredRefinementForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
            
            /**
             * Generated
             */
            bool getHasErased() const;
            
            /**
             * Generated
             */
            void setHasErased(const bool& hasErased);
            
            /**
             * Generated
             */
            bool getHasTriggeredEraseForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
            
            /**
             * Generated
             */
            bool getHasChangedVertexOrCellState() const;
            
            /**
             * Generated
             */
            void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
            
            /**
             * Generated
             */
            bool getIsTraversalInverted() const;
            
            /**
             * Generated
             */
            void setIsTraversalInverted(const bool& isTraversalInverted);
            
            /**
             * Generated
             */
            bool getDeriveAdjacencyInformation() const;
            
            /**
             * Generated
             */
            void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
            
            /**
             * Generated
             */
            std::string toString() const;
            
            /**
             * Generated
             */
            void toString(std::ostream& out) const;
            
            
            PersistentRecords getPersistentRecords() const;
            /**
             * Generated
             */
            SpacetreeGridState convert() const;
            
            
         #ifdef Parallel
            protected:
               static tarch::logging::Log _log;
               
               int _senderRank;
               
            public:
               
               /**
                * Global that represents the mpi datatype.
                */
               static MPI_Datatype Datatype;
               
               /**
                * Initializes the data type for the mpi operations. Has to be called
                * before the very first send or receive operation is called.
                */
               static void initDatatype();
               
               static void shutdownDatatype();
               
               void send(int destination, int tag);
               
               void receive(int source, int tag);
               
               static bool isMessageInQueue(int tag);
               
               int getSenderRank() const;
               
         #endif
            
         };
         
         
      #elif !defined(Parallel)
         /**
          * @author This class was autogenerated by DaStGen
          * 		   DataStructureGenerator (DaStGen), 2007-2009,
          * 		   by Wolfgang Eckhardt
          *
          * 		   build date: 09-12-2010 17:47
          *
          * @date   28/06/2011 13:55
          */
         class peano::applications::heatequation::timestepping::records::SpacetreeGridState { 
            
            public:
               
               typedef peano::applications::heatequation::timestepping::records::SpacetreeGridStatePacked Packed;
               
               struct PersistentRecords {
                  double _omega;
                  double _updateUMax;
                  double _updateUH;
                  double _uMax;
                  double _uH;
                  double _uGlobalMax;
                  double _uGlobalH;
                  int _timeStep;
                  double _timeStepSize;
                  double _time;
                  double _numberOfStencilUpdates;
                  double _minimalAllowedMeshSize;
                  double _maximalAllowedMeshSize;
                  int _activeLevel;
                  tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
                  tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
                  double _numberOfInnerVertices;
                  double _numberOfBoundaryVertices;
                  double _numberOfOuterVertices;
                  double _numberOfInnerCells;
                  double _numberOfOuterCells;
                  int _maxLevel;
                  bool _hasRefined;
                  bool _hasTriggeredRefinementForNextIteration;
                  bool _hasErased;
                  bool _hasTriggeredEraseForNextIteration;
                  bool _hasChangedVertexOrCellState;
                  bool _isTraversalInverted;
                  /**
                   * Generated
                   */
                  PersistentRecords();
                  
                  /**
                   * Generated
                   */
                  PersistentRecords(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
                  
                  /**
                   * Generated
                   */
                  double getOmega() const;
                  
                  /**
                   * Generated
                   */
                  void setOmega(const double& omega);
                  
                  /**
                   * Generated
                   */
                  double getUpdateUMax() const;
                  
                  /**
                   * Generated
                   */
                  void setUpdateUMax(const double& updateUMax);
                  
                  /**
                   * Generated
                   */
                  double getUpdateUH() const;
                  
                  /**
                   * Generated
                   */
                  void setUpdateUH(const double& updateUH);
                  
                  /**
                   * Generated
                   */
                  double getUMax() const;
                  
                  /**
                   * Generated
                   */
                  void setUMax(const double& uMax);
                  
                  /**
                   * Generated
                   */
                  double getUH() const;
                  
                  /**
                   * Generated
                   */
                  void setUH(const double& uH);
                  
                  /**
                   * Generated
                   */
                  double getUGlobalMax() const;
                  
                  /**
                   * Generated
                   */
                  void setUGlobalMax(const double& uGlobalMax);
                  
                  /**
                   * Generated
                   */
                  double getUGlobalH() const;
                  
                  /**
                   * Generated
                   */
                  void setUGlobalH(const double& uGlobalH);
                  
                  /**
                   * Generated
                   */
                  int getTimeStep() const;
                  
                  /**
                   * Generated
                   */
                  void setTimeStep(const int& timeStep);
                  
                  /**
                   * Generated
                   */
                  double getTimeStepSize() const;
                  
                  /**
                   * Generated
                   */
                  void setTimeStepSize(const double& timeStepSize);
                  
                  /**
                   * Generated
                   */
                  double getTime() const;
                  
                  /**
                   * Generated
                   */
                  void setTime(const double& time);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfStencilUpdates() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
                  
                  /**
                   * Generated
                   */
                  double getMinimalAllowedMeshSize() const;
                  
                  /**
                   * Generated
                   */
                  void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
                  
                  /**
                   * Generated
                   */
                  double getMaximalAllowedMeshSize() const;
                  
                  /**
                   * Generated
                   */
                  void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
                  
                  /**
                   * Generated
                   */
                  int getActiveLevel() const;
                  
                  /**
                   * Generated
                   */
                  void setActiveLevel(const int& activeLevel);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerVertices(const double& numberOfInnerVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfBoundaryVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterVertices(const double& numberOfOuterVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerCells(const double& numberOfInnerCells);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterCells(const double& numberOfOuterCells);
                  
                  /**
                   * Generated
                   */
                  int getMaxLevel() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxLevel(const int& maxLevel);
                  
                  /**
                   * Generated
                   */
                  bool getHasRefined() const;
                  
                  /**
                   * Generated
                   */
                  void setHasRefined(const bool& hasRefined);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredRefinementForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasErased() const;
                  
                  /**
                   * Generated
                   */
                  void setHasErased(const bool& hasErased);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredEraseForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasChangedVertexOrCellState() const;
                  
                  /**
                   * Generated
                   */
                  void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
                  
                  /**
                   * Generated
                   */
                  bool getIsTraversalInverted() const;
                  
                  /**
                   * Generated
                   */
                  void setIsTraversalInverted(const bool& isTraversalInverted);
                  
                  
               };
               
            private: 
               PersistentRecords _persistentRecords;
               
            public:
               /**
                * Generated
                */
               SpacetreeGridState();
               
               /**
                * Generated
                */
               SpacetreeGridState(const PersistentRecords& persistentRecords);
               
               /**
                * Generated
                */
               SpacetreeGridState(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
               
               /**
                * Generated
                */
               virtual ~SpacetreeGridState();
               
               /**
                * Generated
                */
               double getOmega() const;
               
               /**
                * Generated
                */
               void setOmega(const double& omega);
               
               /**
                * Generated
                */
               double getUpdateUMax() const;
               
               /**
                * Generated
                */
               void setUpdateUMax(const double& updateUMax);
               
               /**
                * Generated
                */
               double getUpdateUH() const;
               
               /**
                * Generated
                */
               void setUpdateUH(const double& updateUH);
               
               /**
                * Generated
                */
               double getUMax() const;
               
               /**
                * Generated
                */
               void setUMax(const double& uMax);
               
               /**
                * Generated
                */
               double getUH() const;
               
               /**
                * Generated
                */
               void setUH(const double& uH);
               
               /**
                * Generated
                */
               double getUGlobalMax() const;
               
               /**
                * Generated
                */
               void setUGlobalMax(const double& uGlobalMax);
               
               /**
                * Generated
                */
               double getUGlobalH() const;
               
               /**
                * Generated
                */
               void setUGlobalH(const double& uGlobalH);
               
               /**
                * Generated
                */
               int getTimeStep() const;
               
               /**
                * Generated
                */
               void setTimeStep(const int& timeStep);
               
               /**
                * Generated
                */
               double getTimeStepSize() const;
               
               /**
                * Generated
                */
               void setTimeStepSize(const double& timeStepSize);
               
               /**
                * Generated
                */
               double getTime() const;
               
               /**
                * Generated
                */
               void setTime(const double& time);
               
               /**
                * Generated
                */
               double getNumberOfStencilUpdates() const;
               
               /**
                * Generated
                */
               void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
               
               /**
                * Generated
                */
               double getMinimalAllowedMeshSize() const;
               
               /**
                * Generated
                */
               void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
               
               /**
                * Generated
                */
               double getMaximalAllowedMeshSize() const;
               
               /**
                * Generated
                */
               void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
               
               /**
                * Generated
                */
               int getActiveLevel() const;
               
               /**
                * Generated
                */
               void setActiveLevel(const int& activeLevel);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
               
               /**
                * Generated
                */
               void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
               
               /**
                * Generated
                */
               double getMinMeshWidth(int elementIndex) const;
               
               /**
                * Generated
                */
               void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
               
               /**
                * Generated
                */
               void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
               
               /**
                * Generated
                */
               double getMaxMeshWidth(int elementIndex) const;
               
               /**
                * Generated
                */
               void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
               
               /**
                * Generated
                */
               double getNumberOfInnerVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerVertices(const double& numberOfInnerVertices);
               
               /**
                * Generated
                */
               double getNumberOfBoundaryVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
               
               /**
                * Generated
                */
               double getNumberOfOuterVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterVertices(const double& numberOfOuterVertices);
               
               /**
                * Generated
                */
               double getNumberOfInnerCells() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerCells(const double& numberOfInnerCells);
               
               /**
                * Generated
                */
               double getNumberOfOuterCells() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterCells(const double& numberOfOuterCells);
               
               /**
                * Generated
                */
               int getMaxLevel() const;
               
               /**
                * Generated
                */
               void setMaxLevel(const int& maxLevel);
               
               /**
                * Generated
                */
               bool getHasRefined() const;
               
               /**
                * Generated
                */
               void setHasRefined(const bool& hasRefined);
               
               /**
                * Generated
                */
               bool getHasTriggeredRefinementForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
               
               /**
                * Generated
                */
               bool getHasErased() const;
               
               /**
                * Generated
                */
               void setHasErased(const bool& hasErased);
               
               /**
                * Generated
                */
               bool getHasTriggeredEraseForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
               
               /**
                * Generated
                */
               bool getHasChangedVertexOrCellState() const;
               
               /**
                * Generated
                */
               void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
               
               /**
                * Generated
                */
               bool getIsTraversalInverted() const;
               
               /**
                * Generated
                */
               void setIsTraversalInverted(const bool& isTraversalInverted);
               
               /**
                * Generated
                */
               std::string toString() const;
               
               /**
                * Generated
                */
               void toString(std::ostream& out) const;
               
               
               PersistentRecords getPersistentRecords() const;
               /**
                * Generated
                */
               SpacetreeGridStatePacked convert() const;
               
               
            #ifdef Parallel
               protected:
                  static tarch::logging::Log _log;
                  
                  int _senderRank;
                  
               public:
                  
                  /**
                   * Global that represents the mpi datatype.
                   */
                  static MPI_Datatype Datatype;
                  
                  /**
                   * Initializes the data type for the mpi operations. Has to be called
                   * before the very first send or receive operation is called.
                   */
                  static void initDatatype();
                  
                  static void shutdownDatatype();
                  
                  void send(int destination, int tag);
                  
                  void receive(int source, int tag);
                  
                  static bool isMessageInQueue(int tag);
                  
                  int getSenderRank() const;
                  
            #endif
               
            };
            
            /**
             * @author This class was autogenerated by DaStGen
             * 		   DataStructureGenerator (DaStGen), 2007-2009,
             * 		   by Wolfgang Eckhardt
             *
             * 		   build date: 09-12-2010 17:47
             *
             * @date   28/06/2011 13:55
             */
            class peano::applications::heatequation::timestepping::records::SpacetreeGridStatePacked { 
               
               public:
                  
                  struct PersistentRecords {
                     double _omega;
                     double _updateUMax;
                     double _updateUH;
                     double _uMax;
                     double _uH;
                     double _uGlobalMax;
                     double _uGlobalH;
                     int _timeStep;
                     double _timeStepSize;
                     double _time;
                     double _numberOfStencilUpdates;
                     double _minimalAllowedMeshSize;
                     double _maximalAllowedMeshSize;
                     int _activeLevel;
                     tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
                     tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
                     double _numberOfInnerVertices;
                     double _numberOfBoundaryVertices;
                     double _numberOfOuterVertices;
                     double _numberOfInnerCells;
                     double _numberOfOuterCells;
                     int _maxLevel;
                     bool _isTraversalInverted;
                     
                     /** mapping of records:
                     || Member 	|| startbit 	|| length
                      |  hasRefined	| startbit 0	| #bits 1
                      |  hasTriggeredRefinementForNextIteration	| startbit 1	| #bits 1
                      |  hasErased	| startbit 2	| #bits 1
                      |  hasTriggeredEraseForNextIteration	| startbit 3	| #bits 1
                      |  hasChangedVertexOrCellState	| startbit 4	| #bits 1
                      */
                     short int _packedRecords0;
                     
                     /**
                      * Generated
                      */
                     PersistentRecords();
                     
                     /**
                      * Generated
                      */
                     PersistentRecords(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
                     
                     /**
                      * Generated
                      */
                     double getOmega() const;
                     
                     /**
                      * Generated
                      */
                     void setOmega(const double& omega);
                     
                     /**
                      * Generated
                      */
                     double getUpdateUMax() const;
                     
                     /**
                      * Generated
                      */
                     void setUpdateUMax(const double& updateUMax);
                     
                     /**
                      * Generated
                      */
                     double getUpdateUH() const;
                     
                     /**
                      * Generated
                      */
                     void setUpdateUH(const double& updateUH);
                     
                     /**
                      * Generated
                      */
                     double getUMax() const;
                     
                     /**
                      * Generated
                      */
                     void setUMax(const double& uMax);
                     
                     /**
                      * Generated
                      */
                     double getUH() const;
                     
                     /**
                      * Generated
                      */
                     void setUH(const double& uH);
                     
                     /**
                      * Generated
                      */
                     double getUGlobalMax() const;
                     
                     /**
                      * Generated
                      */
                     void setUGlobalMax(const double& uGlobalMax);
                     
                     /**
                      * Generated
                      */
                     double getUGlobalH() const;
                     
                     /**
                      * Generated
                      */
                     void setUGlobalH(const double& uGlobalH);
                     
                     /**
                      * Generated
                      */
                     int getTimeStep() const;
                     
                     /**
                      * Generated
                      */
                     void setTimeStep(const int& timeStep);
                     
                     /**
                      * Generated
                      */
                     double getTimeStepSize() const;
                     
                     /**
                      * Generated
                      */
                     void setTimeStepSize(const double& timeStepSize);
                     
                     /**
                      * Generated
                      */
                     double getTime() const;
                     
                     /**
                      * Generated
                      */
                     void setTime(const double& time);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfStencilUpdates() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
                     
                     /**
                      * Generated
                      */
                     double getMinimalAllowedMeshSize() const;
                     
                     /**
                      * Generated
                      */
                     void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
                     
                     /**
                      * Generated
                      */
                     double getMaximalAllowedMeshSize() const;
                     
                     /**
                      * Generated
                      */
                     void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
                     
                     /**
                      * Generated
                      */
                     int getActiveLevel() const;
                     
                     /**
                      * Generated
                      */
                     void setActiveLevel(const int& activeLevel);
                     
                     /**
                      * Generated
                      */
                     tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
                     
                     /**
                      * Generated
                      */
                     void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
                     
                     /**
                      * Generated
                      */
                     tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
                     
                     /**
                      * Generated
                      */
                     void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfInnerVertices() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfInnerVertices(const double& numberOfInnerVertices);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfBoundaryVertices() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfOuterVertices() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfOuterVertices(const double& numberOfOuterVertices);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfInnerCells() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfInnerCells(const double& numberOfInnerCells);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfOuterCells() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfOuterCells(const double& numberOfOuterCells);
                     
                     /**
                      * Generated
                      */
                     int getMaxLevel() const;
                     
                     /**
                      * Generated
                      */
                     void setMaxLevel(const int& maxLevel);
                     
                     /**
                      * Generated
                      */
                     bool getHasRefined() const;
                     
                     /**
                      * Generated
                      */
                     void setHasRefined(const bool& hasRefined);
                     
                     /**
                      * Generated
                      */
                     bool getHasTriggeredRefinementForNextIteration() const;
                     
                     /**
                      * Generated
                      */
                     void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
                     
                     /**
                      * Generated
                      */
                     bool getHasErased() const;
                     
                     /**
                      * Generated
                      */
                     void setHasErased(const bool& hasErased);
                     
                     /**
                      * Generated
                      */
                     bool getHasTriggeredEraseForNextIteration() const;
                     
                     /**
                      * Generated
                      */
                     void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
                     
                     /**
                      * Generated
                      */
                     bool getHasChangedVertexOrCellState() const;
                     
                     /**
                      * Generated
                      */
                     void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
                     
                     /**
                      * Generated
                      */
                     bool getIsTraversalInverted() const;
                     
                     /**
                      * Generated
                      */
                     void setIsTraversalInverted(const bool& isTraversalInverted);
                     
                     
                  };
                  
               private: 
                  PersistentRecords _persistentRecords;
                  
               public:
                  /**
                   * Generated
                   */
                  SpacetreeGridStatePacked();
                  
                  /**
                   * Generated
                   */
                  SpacetreeGridStatePacked(const PersistentRecords& persistentRecords);
                  
                  /**
                   * Generated
                   */
                  SpacetreeGridStatePacked(const double& omega, const double& updateUMax, const double& updateUH, const double& uMax, const double& uH, const double& uGlobalMax, const double& uGlobalH, const int& timeStep, const double& timeStepSize, const double& time, const double& numberOfStencilUpdates, const double& minimalAllowedMeshSize, const double& maximalAllowedMeshSize, const int& activeLevel, const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
                  
                  /**
                   * Generated
                   */
                  virtual ~SpacetreeGridStatePacked();
                  
                  /**
                   * Generated
                   */
                  double getOmega() const;
                  
                  /**
                   * Generated
                   */
                  void setOmega(const double& omega);
                  
                  /**
                   * Generated
                   */
                  double getUpdateUMax() const;
                  
                  /**
                   * Generated
                   */
                  void setUpdateUMax(const double& updateUMax);
                  
                  /**
                   * Generated
                   */
                  double getUpdateUH() const;
                  
                  /**
                   * Generated
                   */
                  void setUpdateUH(const double& updateUH);
                  
                  /**
                   * Generated
                   */
                  double getUMax() const;
                  
                  /**
                   * Generated
                   */
                  void setUMax(const double& uMax);
                  
                  /**
                   * Generated
                   */
                  double getUH() const;
                  
                  /**
                   * Generated
                   */
                  void setUH(const double& uH);
                  
                  /**
                   * Generated
                   */
                  double getUGlobalMax() const;
                  
                  /**
                   * Generated
                   */
                  void setUGlobalMax(const double& uGlobalMax);
                  
                  /**
                   * Generated
                   */
                  double getUGlobalH() const;
                  
                  /**
                   * Generated
                   */
                  void setUGlobalH(const double& uGlobalH);
                  
                  /**
                   * Generated
                   */
                  int getTimeStep() const;
                  
                  /**
                   * Generated
                   */
                  void setTimeStep(const int& timeStep);
                  
                  /**
                   * Generated
                   */
                  double getTimeStepSize() const;
                  
                  /**
                   * Generated
                   */
                  void setTimeStepSize(const double& timeStepSize);
                  
                  /**
                   * Generated
                   */
                  double getTime() const;
                  
                  /**
                   * Generated
                   */
                  void setTime(const double& time);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfStencilUpdates() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfStencilUpdates(const double& numberOfStencilUpdates);
                  
                  /**
                   * Generated
                   */
                  double getMinimalAllowedMeshSize() const;
                  
                  /**
                   * Generated
                   */
                  void setMinimalAllowedMeshSize(const double& minimalAllowedMeshSize);
                  
                  /**
                   * Generated
                   */
                  double getMaximalAllowedMeshSize() const;
                  
                  /**
                   * Generated
                   */
                  void setMaximalAllowedMeshSize(const double& maximalAllowedMeshSize);
                  
                  /**
                   * Generated
                   */
                  int getActiveLevel() const;
                  
                  /**
                   * Generated
                   */
                  void setActiveLevel(const int& activeLevel);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getMinMeshWidth(int elementIndex) const;
                  
                  /**
                   * Generated
                   */
                  void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getMaxMeshWidth(int elementIndex) const;
                  
                  /**
                   * Generated
                   */
                  void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerVertices(const double& numberOfInnerVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfBoundaryVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterVertices(const double& numberOfOuterVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerCells(const double& numberOfInnerCells);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterCells(const double& numberOfOuterCells);
                  
                  /**
                   * Generated
                   */
                  int getMaxLevel() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxLevel(const int& maxLevel);
                  
                  /**
                   * Generated
                   */
                  bool getHasRefined() const;
                  
                  /**
                   * Generated
                   */
                  void setHasRefined(const bool& hasRefined);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredRefinementForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasErased() const;
                  
                  /**
                   * Generated
                   */
                  void setHasErased(const bool& hasErased);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredEraseForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasChangedVertexOrCellState() const;
                  
                  /**
                   * Generated
                   */
                  void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
                  
                  /**
                   * Generated
                   */
                  bool getIsTraversalInverted() const;
                  
                  /**
                   * Generated
                   */
                  void setIsTraversalInverted(const bool& isTraversalInverted);
                  
                  /**
                   * Generated
                   */
                  std::string toString() const;
                  
                  /**
                   * Generated
                   */
                  void toString(std::ostream& out) const;
                  
                  
                  PersistentRecords getPersistentRecords() const;
                  /**
                   * Generated
                   */
                  SpacetreeGridState convert() const;
                  
                  
               #ifdef Parallel
                  protected:
                     static tarch::logging::Log _log;
                     
                     int _senderRank;
                     
                  public:
                     
                     /**
                      * Global that represents the mpi datatype.
                      */
                     static MPI_Datatype Datatype;
                     
                     /**
                      * Initializes the data type for the mpi operations. Has to be called
                      * before the very first send or receive operation is called.
                      */
                     static void initDatatype();
                     
                     static void shutdownDatatype();
                     
                     void send(int destination, int tag);
                     
                     void receive(int source, int tag);
                     
                     static bool isMessageInQueue(int tag);
                     
                     int getSenderRank() const;
                     
               #endif
                  
               };
               
               
            
         #endif
         
         #endif
         
