// Copyright (C) 2009 Technische Universitaet Muenchen 
// This file is part of the Peano project. For conditions of distribution and 
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef PEANO_APPLICATIONS_HEATEQUATION_TIMESTEPPING_RUNNERS_TimeSteppingBatchJobRunner__FOR_SPACETREE_GRID_H_
#define PEANO_APPLICATIONS_HEATEQUATION_TIMESTEPPING_RUNNERS_TimeSteppingBatchJobRunner__FOR_SPACETREE_GRID_H_ 


#include "peano/applications/heatequation/timestepping/configurations/TimeSteppingBatchJobConfigurationForSpacetreeGrid.h"

namespace peano { 
  namespace applications { 
    namespace heatequation { 
      namespace timestepping {
    namespace runners {
      class TimeSteppingBatchJobRunnerForSpacetreeGrid;
    }
    namespace configurations {
      class TimeSteppingBatchJobConfigurationForSpacetreeGrid;
    }
    namespace repositories {
      class TimeSteppingBatchJobRepositoryForSpacetreeGrid;
    }
}
}
}
}



/**
 * Runner for the regular grid.
 *
 * @author Generated by the PeProt (Peano Rapid Prototyping) tool. 
 */
class peano::applications::heatequation::timestepping::runners::TimeSteppingBatchJobRunnerForSpacetreeGrid {
  private:
    int runAsMaster(peano::applications::heatequation::timestepping::repositories::TimeSteppingBatchJobRepositoryForSpacetreeGrid& repository, const peano::applications::heatequation::timestepping::configurations::TimeSteppingBatchJobConfigurationForSpacetreeGrid& configuration);
    
    #ifdef Parallel
    int runAsClient(peano::applications::heatequation::timestepping::repositories::TimeSteppingBatchJobRepositoryForSpacetreeGrid& repository);
    #endif

    static tarch::logging::Log _log;
  public:
    TimeSteppingBatchJobRunnerForSpacetreeGrid();
    virtual ~TimeSteppingBatchJobRunnerForSpacetreeGrid();

    /**
     * Executes the run for one configuration.
     * 
     * Whenever the configuration file parser encounters a tag corresponding to
     * a regular grid runner, it tells the corresponding configuration class
     * configurations::peano::applications::heatequation::timestepping::configurations::TimeSteppingBatchJobConfigurationForRegularGrid 
     * to create an instance of this class and to parse the configuration file. 
     * If the latter is valid, Peano afterwards calls the runner's run() routine 
     * and passes it the configuration instance. 
     *
     * @param configuration Valid configuration for this experiment run.
     */
    int run(const peano::applications::heatequation::timestepping::configurations::TimeSteppingBatchJobConfigurationForSpacetreeGrid& configuration); 
};

#endif
