// Copyright (C) 2009 Technische Universitaet Muenchen
// This file is part of the Peano project. For conditions of distribution and
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef _PEANO_APPLICATIONS_LATTICEBOLTZMANN_GAUSSIANRANDOMNUMBERGENERATOR_H_
#define _PEANO_APPLICATIONS_LATTICEBOLTZMANN_GAUSSIANRANDOMNUMBERGENERATOR_H_

#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <cstdlib>

namespace peano {
  namespace applications {
    namespace latticeboltzmann {
      class GaussianRandomNumberGenerator;
    }
  }
}


/** generates Gaussian random numbers with zero mean and unit variance
 *
 * @author Philipp Neumann
 */
class peano::applications::latticeboltzmann::GaussianRandomNumberGenerator {

  public:
    /** constructor */
    GaussianRandomNumberGenerator();

    /** destructor */
    ~GaussianRandomNumberGenerator();

    /** returns a Gaussian random number with zero mean and unit variance */
    double getGaussianRandomNumber();

  private:

    /** holds to Gaussian numbers generated by the polar method */
    tarch::la::Vector<2,double> _randomNumbers;

    bool _isFirstRandomNumber;

    /** for logging */
    static tarch::logging::Log _log;
};

#endif // _PEANO_APPLICATIONS_LATTICEBOLTZMANN_GAUSSIANRANDOMNUMBERGENERATOR_H_
