// Copyright (C) 2009 Technische Universitaet Muenchen 
// This file is part of the Peano project. For conditions of distribution and 
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef PEANO_APPLICATIONS_FAXEN_LBF_RUNNERS_LBFBatchJobRunner__FOR_SPACETREE_GRID_H_
#define PEANO_APPLICATIONS_FAXEN_LBF_RUNNERS_LBFBatchJobRunner__FOR_SPACETREE_GRID_H_ 


#include "peano/applications/faxen/lbf/configurations/LBFBatchJobConfigurationForSpacetreeGrid.h"

namespace peano { 
  namespace applications { 
    namespace faxen { 
      namespace lbf {
    namespace runners {
      class LBFBatchJobRunnerForSpacetreeGrid;
    }
    namespace configurations {
      class LBFBatchJobConfigurationForSpacetreeGrid;
    }
    namespace repositories {
      class LBFBatchJobRepositoryForSpacetreeGrid;
    }
}
}
}
}



/**
 * Runner for the regular grid.
 *
 * @author Generated by the PeProt (Peano Rapid Prototyping) tool. 
 */
class peano::applications::faxen::lbf::runners::LBFBatchJobRunnerForSpacetreeGrid {
  private:
    int runAsMaster(peano::applications::faxen::lbf::repositories::LBFBatchJobRepositoryForSpacetreeGrid& repository);
    
    #ifdef Parallel
    int runAsClient(peano::applications::faxen::lbf::repositories::LBFBatchJobRepositoryForSpacetreeGrid& repository);
    #endif
  public:
    LBFBatchJobRunnerForSpacetreeGrid();
    virtual ~LBFBatchJobRunnerForSpacetreeGrid();

    /**
     * Executes the run for one configuration.
     * 
     * Whenever the configuration file parser encounters a tag corresponding to
     * a regular grid runner, it tells the corresponding configuration class
     * configurations::peano::applications::faxen::lbf::configurations::LBFBatchJobConfigurationForRegularGrid 
     * to create an instance of this class and to parse the configuration file. 
     * If the latter is valid, Peano afterwards calls the runner's run() routine 
     * and passes it the configuration instance. 
     *
     * @param configuration Valid configuration for this experiment run.
     */
    int run(const peano::applications::faxen::lbf::configurations::LBFBatchJobConfigurationForSpacetreeGrid& configuration); 
};

#endif
