#ifndef _PEANO_KERNEL_REGULARGRID_TESTS_RECORDS_TEST_CELL_H_
#define _PEANO_KERNEL_REGULARGRID_TESTS_RECORDS_TEST_CELL_H_

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>
#include "peano/utils/Globals.h"

namespace peano {
   namespace kernel {
      namespace regulargrid {
         namespace tests {
           namespace records {
             class TestCell;
             class TestCellPacked;
           }
         }
      }
   }
}

/**
 * @author This class was autogenerated by DaStGen
 * 		   DataStructureGenerator (DaStGen), 2007-2009,
 * 		   by Wolfgang Eckhardt
 *
 * 		   build date: 17-10-2010 09:35
 *
 * @date   17/10/2010 09:35
 */
class peano::kernel::regulargrid::tests::records::TestCell {
   
   public:
      
      typedef peano::kernel::regulargrid::tests::records::TestCellPacked Packed;
      
      struct PersistentRecords {
         bool _isInside;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const bool& isInside);
         
         /**
          * Generated
          */
         bool getIsInside() const;
         
         /**
          * Generated
          */
         void setIsInside(const bool& isInside);
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      TestCell();
      
      /**
       * Generated
       */
      TestCell(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      TestCell(const bool& isInside);
      
      /**
       * Generated
       */
      virtual ~TestCell();
      
      /**
       * Generated
       */
      bool getIsInside() const;
      
      /**
       * Generated
       */
      void setIsInside(const bool& isInside);
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      TestCellPacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          */
         static MPI_Datatype Datatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag);
         
         void receive(int source, int tag);
         
         static bool isMessageInQueue(int tag);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 17-10-2010 09:35
    *
    * @date   17/10/2010 09:35
    */
   class peano::kernel::regulargrid::tests::records::TestCellPacked {
      
      public:
         
         struct PersistentRecords {
            
            /** mapping of records:
            || Member 	|| startbit 	|| length
             |  isInside	| startbit 0	| #bits 1
             */
            short int _packedRecords0;
            
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const bool& isInside);
            
            /**
             * Generated
             */
            bool getIsInside() const;
            
            /**
             * Generated
             */
            void setIsInside(const bool& isInside);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         TestCellPacked();
         
         /**
          * Generated
          */
         TestCellPacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         TestCellPacked(const bool& isInside);
         
         /**
          * Generated
          */
         virtual ~TestCellPacked();
         
         /**
          * Generated
          */
         bool getIsInside() const;
         
         /**
          * Generated
          */
         void setIsInside(const bool& isInside);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         TestCell convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
