#ifndef _PEANO_KERNEL_REGULARGRID_TESTS_RECORDS_TEST_VERTEX_H_
#define _PEANO_KERNEL_REGULARGRID_TESTS_RECORDS_TEST_VERTEX_H_

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>
#include "peano/utils/Globals.h"

namespace peano {
   namespace kernel {
      namespace regulargrid {
         namespace tests {
           namespace records {
             class TestVertex;
             class TestVertexPacked;
           }
         }
      }
   }
}

#if !defined(Debug)
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 17-10-2010 09:35
    *
    * @date   17/10/2010 09:35
    */
   class peano::kernel::regulargrid::tests::records::TestVertex {
      
      public:
         
         typedef peano::kernel::regulargrid::tests::records::TestVertexPacked Packed;
         
         enum InsideOutsideDomain {
            Inside = 0, Outside = 1, Boundary = 2
         };
         
         struct PersistentRecords {
            InsideOutsideDomain _insideOutsideDomain;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const InsideOutsideDomain& insideOutsideDomain);
            
            /**
             * Generated
             */
            InsideOutsideDomain getInsideOutsideDomain() const;
            
            /**
             * Generated
             */
            void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         TestVertex();
         
         /**
          * Generated
          */
         TestVertex(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         TestVertex(const InsideOutsideDomain& insideOutsideDomain);
         
         /**
          * Generated
          */
         virtual ~TestVertex();
         
         /**
          * Generated
          */
         InsideOutsideDomain getInsideOutsideDomain() const;
         
         /**
          * Generated
          */
         void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
         
         /**
          * Generated
          */
         static std::string toString(const InsideOutsideDomain& param);
         
         /**
          * Generated
          */
         static std::string getInsideOutsideDomainMapping();
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         TestVertexPacked convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      /**
       * @author This class was autogenerated by DaStGen
       * 		   DataStructureGenerator (DaStGen), 2007-2009,
       * 		   by Wolfgang Eckhardt
       *
       * 		   build date: 17-10-2010 09:35
       *
       * @date   17/10/2010 09:35
       */
      class peano::kernel::regulargrid::tests::records::TestVertexPacked {
         
         public:
            
            typedef peano::kernel::regulargrid::tests::records::TestVertex::InsideOutsideDomain InsideOutsideDomain;
            
            struct PersistentRecords {
               
               /** mapping of records:
               || Member 	|| startbit 	|| length
                |  insideOutsideDomain	| startbit 0	| #bits 2
                */
               short int _packedRecords0;
               
               /**
                * Generated
                */
               PersistentRecords();
               
               /**
                * Generated
                */
               PersistentRecords(const InsideOutsideDomain& insideOutsideDomain);
               
               /**
                * Generated
                */
               InsideOutsideDomain getInsideOutsideDomain() const;
               
               /**
                * Generated
                */
               void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
               
               
            };
            
         private: 
            PersistentRecords _persistentRecords;
            
         public:
            /**
             * Generated
             */
            TestVertexPacked();
            
            /**
             * Generated
             */
            TestVertexPacked(const PersistentRecords& persistentRecords);
            
            /**
             * Generated
             */
            TestVertexPacked(const InsideOutsideDomain& insideOutsideDomain);
            
            /**
             * Generated
             */
            virtual ~TestVertexPacked();
            
            /**
             * Generated
             */
            InsideOutsideDomain getInsideOutsideDomain() const;
            
            /**
             * Generated
             */
            void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
            
            /**
             * Generated
             */
            static std::string toString(const InsideOutsideDomain& param);
            
            /**
             * Generated
             */
            static std::string getInsideOutsideDomainMapping();
            
            /**
             * Generated
             */
            std::string toString() const;
            
            /**
             * Generated
             */
            void toString(std::ostream& out) const;
            
            
            PersistentRecords getPersistentRecords() const;
            /**
             * Generated
             */
            TestVertex convert() const;
            
            
         #ifdef Parallel
            protected:
               static tarch::logging::Log _log;
               
               int _senderRank;
               
            public:
               
               /**
                * Global that represents the mpi datatype.
                */
               static MPI_Datatype Datatype;
               
               /**
                * Initializes the data type for the mpi operations. Has to be called
                * before the very first send or receive operation is called.
                */
               static void initDatatype();
               
               static void shutdownDatatype();
               
               void send(int destination, int tag);
               
               void receive(int source, int tag);
               
               static bool isMessageInQueue(int tag);
               
               int getSenderRank() const;
               
         #endif
            
         };
         
         
      #elif defined(Debug)
         /**
          * @author This class was autogenerated by DaStGen
          * 		   DataStructureGenerator (DaStGen), 2007-2009,
          * 		   by Wolfgang Eckhardt
          *
          * 		   build date: 17-10-2010 09:35
          *
          * @date   17/10/2010 09:35
          */
         class peano::kernel::regulargrid::tests::records::TestVertex {
            
            public:
               
               typedef peano::kernel::regulargrid::tests::records::TestVertexPacked Packed;
               
               enum InsideOutsideDomain {
                  Inside = 0, Outside = 1, Boundary = 2
               };
               
               struct PersistentRecords {
                  InsideOutsideDomain _insideOutsideDomain;
                  tarch::la::Vector<DIMENSIONS,double> _x;
                  /**
                   * Generated
                   */
                  PersistentRecords();
                  
                  /**
                   * Generated
                   */
                  PersistentRecords(const InsideOutsideDomain& insideOutsideDomain, const tarch::la::Vector<DIMENSIONS,double>& x);
                  
                  /**
                   * Generated
                   */
                  InsideOutsideDomain getInsideOutsideDomain() const;
                  
                  /**
                   * Generated
                   */
                  void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getX() const;
                  
                  /**
                   * Generated
                   */
                  void setX(const tarch::la::Vector<DIMENSIONS,double>& x);
                  
                  
               };
               
            private: 
               PersistentRecords _persistentRecords;
               
            public:
               /**
                * Generated
                */
               TestVertex();
               
               /**
                * Generated
                */
               TestVertex(const PersistentRecords& persistentRecords);
               
               /**
                * Generated
                */
               TestVertex(const InsideOutsideDomain& insideOutsideDomain, const tarch::la::Vector<DIMENSIONS,double>& x);
               
               /**
                * Generated
                */
               virtual ~TestVertex();
               
               /**
                * Generated
                */
               InsideOutsideDomain getInsideOutsideDomain() const;
               
               /**
                * Generated
                */
               void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getX() const;
               
               /**
                * Generated
                */
               void setX(const tarch::la::Vector<DIMENSIONS,double>& x);
               
               /**
                * Generated
                */
               double getX(int elementIndex) const;
               
               /**
                * Generated
                */
               void setX(int elementIndex, const double& x);
               
               /**
                * Generated
                */
               static std::string toString(const InsideOutsideDomain& param);
               
               /**
                * Generated
                */
               static std::string getInsideOutsideDomainMapping();
               
               /**
                * Generated
                */
               std::string toString() const;
               
               /**
                * Generated
                */
               void toString(std::ostream& out) const;
               
               
               PersistentRecords getPersistentRecords() const;
               /**
                * Generated
                */
               TestVertexPacked convert() const;
               
               
            #ifdef Parallel
               protected:
                  static tarch::logging::Log _log;
                  
                  int _senderRank;
                  
               public:
                  
                  /**
                   * Global that represents the mpi datatype.
                   */
                  static MPI_Datatype Datatype;
                  
                  /**
                   * Initializes the data type for the mpi operations. Has to be called
                   * before the very first send or receive operation is called.
                   */
                  static void initDatatype();
                  
                  static void shutdownDatatype();
                  
                  void send(int destination, int tag);
                  
                  void receive(int source, int tag);
                  
                  static bool isMessageInQueue(int tag);
                  
                  int getSenderRank() const;
                  
            #endif
               
            };
            
            /**
             * @author This class was autogenerated by DaStGen
             * 		   DataStructureGenerator (DaStGen), 2007-2009,
             * 		   by Wolfgang Eckhardt
             *
             * 		   build date: 17-10-2010 09:35
             *
             * @date   17/10/2010 09:35
             */
            class peano::kernel::regulargrid::tests::records::TestVertexPacked {
               
               public:
                  
                  typedef peano::kernel::regulargrid::tests::records::TestVertex::InsideOutsideDomain InsideOutsideDomain;
                  
                  struct PersistentRecords {
                     tarch::la::Vector<DIMENSIONS,double> _x;
                     
                     /** mapping of records:
                     || Member 	|| startbit 	|| length
                      |  insideOutsideDomain	| startbit 0	| #bits 2
                      */
                     short int _packedRecords0;
                     
                     /**
                      * Generated
                      */
                     PersistentRecords();
                     
                     /**
                      * Generated
                      */
                     PersistentRecords(const InsideOutsideDomain& insideOutsideDomain, const tarch::la::Vector<DIMENSIONS,double>& x);
                     
                     /**
                      * Generated
                      */
                     InsideOutsideDomain getInsideOutsideDomain() const;
                     
                     /**
                      * Generated
                      */
                     void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
                     
                     /**
                      * Generated
                      */
                     tarch::la::Vector<DIMENSIONS,double> getX() const;
                     
                     /**
                      * Generated
                      */
                     void setX(const tarch::la::Vector<DIMENSIONS,double>& x);
                     
                     
                  };
                  
               private: 
                  PersistentRecords _persistentRecords;
                  
               public:
                  /**
                   * Generated
                   */
                  TestVertexPacked();
                  
                  /**
                   * Generated
                   */
                  TestVertexPacked(const PersistentRecords& persistentRecords);
                  
                  /**
                   * Generated
                   */
                  TestVertexPacked(const InsideOutsideDomain& insideOutsideDomain, const tarch::la::Vector<DIMENSIONS,double>& x);
                  
                  /**
                   * Generated
                   */
                  virtual ~TestVertexPacked();
                  
                  /**
                   * Generated
                   */
                  InsideOutsideDomain getInsideOutsideDomain() const;
                  
                  /**
                   * Generated
                   */
                  void setInsideOutsideDomain(const InsideOutsideDomain& insideOutsideDomain);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getX() const;
                  
                  /**
                   * Generated
                   */
                  void setX(const tarch::la::Vector<DIMENSIONS,double>& x);
                  
                  /**
                   * Generated
                   */
                  double getX(int elementIndex) const;
                  
                  /**
                   * Generated
                   */
                  void setX(int elementIndex, const double& x);
                  
                  /**
                   * Generated
                   */
                  static std::string toString(const InsideOutsideDomain& param);
                  
                  /**
                   * Generated
                   */
                  static std::string getInsideOutsideDomainMapping();
                  
                  /**
                   * Generated
                   */
                  std::string toString() const;
                  
                  /**
                   * Generated
                   */
                  void toString(std::ostream& out) const;
                  
                  
                  PersistentRecords getPersistentRecords() const;
                  /**
                   * Generated
                   */
                  TestVertex convert() const;
                  
                  
               #ifdef Parallel
                  protected:
                     static tarch::logging::Log _log;
                     
                     int _senderRank;
                     
                  public:
                     
                     /**
                      * Global that represents the mpi datatype.
                      */
                     static MPI_Datatype Datatype;
                     
                     /**
                      * Initializes the data type for the mpi operations. Has to be called
                      * before the very first send or receive operation is called.
                      */
                     static void initDatatype();
                     
                     static void shutdownDatatype();
                     
                     void send(int destination, int tag);
                     
                     void receive(int source, int tag);
                     
                     static bool isMessageInQueue(int tag);
                     
                     int getSenderRank() const;
                     
               #endif
                  
               };
               
               
            
         #endif
         
         #endif
         
