// Copyright (C) 2009 Technische Universitaet Muenchen 
// This file is part of the Peano project. For conditions of distribution and 
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef PEANO_APPLICATIONS_PIC_DEMO2_RUNNERS_PICBatchJobRunner__FOR_SPACETREE_GRID_H_
#define PEANO_APPLICATIONS_PIC_DEMO2_RUNNERS_PICBatchJobRunner__FOR_SPACETREE_GRID_H_ 


#include "peano/applications/pic/demo2/configurations/PICBatchJobConfigurationForSpacetreeGrid.h"

namespace peano { 
  namespace applications { 
    namespace pic { 
      namespace demo2 {
    namespace runners {
      class PICBatchJobRunnerForSpacetreeGrid;
    }
    namespace configurations {
      class PICBatchJobConfigurationForSpacetreeGrid;
    }
    namespace repositories {
      class PICBatchJobRepositoryForSpacetreeGrid;
    }
}
}
}
}



/**
 * Runner for the regular grid.
 *
 * @author Generated by the PeProt (Peano Rapid Prototyping) tool. 
 */
class peano::applications::pic::demo2::runners::PICBatchJobRunnerForSpacetreeGrid {
  private:
    int runAsMaster(peano::applications::pic::demo2::repositories::PICBatchJobRepositoryForSpacetreeGrid& repository);
    
    #ifdef Parallel
    int runAsClient(peano::applications::pic::demo2::repositories::PICBatchJobRepositoryForSpacetreeGrid& repository);
    #endif
  public:
    PICBatchJobRunnerForSpacetreeGrid();
    virtual ~PICBatchJobRunnerForSpacetreeGrid();

    /**
     * Executes the run for one configuration.
     * 
     * Whenever the configuration file parser encounters a tag corresponding to
     * a regular grid runner, it tells the corresponding configuration class
     * configurations::peano::applications::pic::demo2::configurations::PICBatchJobConfigurationForRegularGrid 
     * to create an instance of this class and to parse the configuration file. 
     * If the latter is valid, Peano afterwards calls the runner's run() routine 
     * and passes it the configuration instance. 
     *
     * @param configuration Valid configuration for this experiment run.
     */
    int run(const peano::applications::pic::demo2::configurations::PICBatchJobConfigurationForSpacetreeGrid& configuration); 
};

#endif
