// Copyright (C) 2009 Technische Universitaet Muenchen 
// This file is part of the Peano project. For conditions of distribution and 
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef PEANO_APPLICATIONS_PUREGRID_RUNNERS_PuregridBatchJobRunner__FOR_SPACETREE_GRID_H_
#define PEANO_APPLICATIONS_PUREGRID_RUNNERS_PuregridBatchJobRunner__FOR_SPACETREE_GRID_H_ 


#include "peano/applications/puregrid/configurations/PuregridBatchJobConfigurationForSpacetreeGrid.h"

namespace peano { 
  namespace applications { 
    namespace puregrid {
    namespace runners {
      class PuregridBatchJobRunnerForSpacetreeGrid;
    }
    namespace configurations {
      class PuregridBatchJobConfigurationForSpacetreeGrid;
    }
    namespace repositories {
      class PuregridBatchJobRepositoryForSpacetreeGrid;
    }
}
}
}



/**
 * Runner for the regular grid.
 *
 * @author Generated by the RaPeP (Peano Rapid Prototyping) tool. 
 */
class peano::applications::puregrid::runners::PuregridBatchJobRunnerForSpacetreeGrid {
  private:
    int runAsMaster(peano::applications::puregrid::repositories::PuregridBatchJobRepositoryForSpacetreeGrid& repository);
    
    #ifdef Parallel
    int runAsClient(peano::applications::puregrid::repositories::PuregridBatchJobRepositoryForSpacetreeGrid& repository);
    #endif
  public:
    PuregridBatchJobRunnerForSpacetreeGrid();
    virtual ~PuregridBatchJobRunnerForSpacetreeGrid();

    /**
     * Executes the run for one configuration.
     * 
     * Whenever the configuration file parser encounters a tag corresponding to
     * a regular grid runner, it tells the corresponding configuration class
     * configurations::peano::applications::puregrid::configurations::PuregridBatchJobConfigurationForRegularGrid 
     * to create an instance of this class and to parse the configuration file. 
     * If the latter is valid, Peano afterwards calls the runner's run() routine 
     * and passes it the configuration instance. 
     *
     * @param configuration Valid configuration for this experiment run.
     */
    int run(const peano::applications::puregrid::configurations::PuregridBatchJobConfigurationForSpacetreeGrid& configuration); 
};

#endif
