#ifndef _PEANO_APPLICATIONS_SHALLOWWATER_RECORDS_REGULARGRIDCELL_H
#define _PEANO_APPLICATIONS_SHALLOWWATER_RECORDS_REGULARGRIDCELL_H

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>
#include "peano/utils/Globals.h"

namespace peano {
   namespace applications {
      namespace shallowwater {
         namespace records {
            class RegularGridCell;
            class RegularGridCellPacked;
         }
      }
   }
}

/**
 * @author This class was autogenerated by DaStGen
 * 		   DataStructureGenerator (DaStGen), 2007-2009,
 * 		   by Wolfgang Eckhardt
 *
 * 		   build date: 09-12-2010 17:47
 *
 * @date   26/05/2011 08:53
 */
class peano::applications::shallowwater::records::RegularGridCell { 
   
   public:
      
      typedef peano::applications::shallowwater::records::RegularGridCellPacked Packed;
      
      struct PersistentRecords {
         double _heightWater;
         double _heightSeabed;
         double _momentumX;
         double _momentumY;
         bool _isInside;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const double& heightWater, const double& heightSeabed, const double& momentumX, const double& momentumY, const bool& isInside);
         
         /**
          * Generated
          */
         double getHeightWater() const;
         
         /**
          * Generated
          */
         void setHeightWater(const double& heightWater);
         
         /**
          * Generated
          */
         double getHeightSeabed() const;
         
         /**
          * Generated
          */
         void setHeightSeabed(const double& heightSeabed);
         
         /**
          * Generated
          */
         double getMomentumX() const;
         
         /**
          * Generated
          */
         void setMomentumX(const double& momentumX);
         
         /**
          * Generated
          */
         double getMomentumY() const;
         
         /**
          * Generated
          */
         void setMomentumY(const double& momentumY);
         
         /**
          * Generated
          */
         bool getIsInside() const;
         
         /**
          * Generated
          */
         void setIsInside(const bool& isInside);
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      RegularGridCell();
      
      /**
       * Generated
       */
      RegularGridCell(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      RegularGridCell(const double& heightWater, const double& heightSeabed, const double& momentumX, const double& momentumY, const bool& isInside);
      
      /**
       * Generated
       */
      virtual ~RegularGridCell();
      
      /**
       * Generated
       */
      double getHeightWater() const;
      
      /**
       * Generated
       */
      void setHeightWater(const double& heightWater);
      
      /**
       * Generated
       */
      double getHeightSeabed() const;
      
      /**
       * Generated
       */
      void setHeightSeabed(const double& heightSeabed);
      
      /**
       * Generated
       */
      double getMomentumX() const;
      
      /**
       * Generated
       */
      void setMomentumX(const double& momentumX);
      
      /**
       * Generated
       */
      double getMomentumY() const;
      
      /**
       * Generated
       */
      void setMomentumY(const double& momentumY);
      
      /**
       * Generated
       */
      bool getIsInside() const;
      
      /**
       * Generated
       */
      void setIsInside(const bool& isInside);
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      RegularGridCellPacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          */
         static MPI_Datatype Datatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag);
         
         void receive(int source, int tag);
         
         static bool isMessageInQueue(int tag);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 09-12-2010 17:47
    *
    * @date   26/05/2011 08:53
    */
   class peano::applications::shallowwater::records::RegularGridCellPacked { 
      
      public:
         
         struct PersistentRecords {
            double _heightWater;
            double _heightSeabed;
            double _momentumX;
            double _momentumY;
            
            /** mapping of records:
            || Member 	|| startbit 	|| length
             |  isInside	| startbit 0	| #bits 1
             */
            short int _packedRecords0;
            
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const double& heightWater, const double& heightSeabed, const double& momentumX, const double& momentumY, const bool& isInside);
            
            /**
             * Generated
             */
            double getHeightWater() const;
            
            /**
             * Generated
             */
            void setHeightWater(const double& heightWater);
            
            /**
             * Generated
             */
            double getHeightSeabed() const;
            
            /**
             * Generated
             */
            void setHeightSeabed(const double& heightSeabed);
            
            /**
             * Generated
             */
            double getMomentumX() const;
            
            /**
             * Generated
             */
            void setMomentumX(const double& momentumX);
            
            /**
             * Generated
             */
            double getMomentumY() const;
            
            /**
             * Generated
             */
            void setMomentumY(const double& momentumY);
            
            /**
             * Generated
             */
            bool getIsInside() const;
            
            /**
             * Generated
             */
            void setIsInside(const bool& isInside);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         RegularGridCellPacked();
         
         /**
          * Generated
          */
         RegularGridCellPacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         RegularGridCellPacked(const double& heightWater, const double& heightSeabed, const double& momentumX, const double& momentumY, const bool& isInside);
         
         /**
          * Generated
          */
         virtual ~RegularGridCellPacked();
         
         /**
          * Generated
          */
         double getHeightWater() const;
         
         /**
          * Generated
          */
         void setHeightWater(const double& heightWater);
         
         /**
          * Generated
          */
         double getHeightSeabed() const;
         
         /**
          * Generated
          */
         void setHeightSeabed(const double& heightSeabed);
         
         /**
          * Generated
          */
         double getMomentumX() const;
         
         /**
          * Generated
          */
         void setMomentumX(const double& momentumX);
         
         /**
          * Generated
          */
         double getMomentumY() const;
         
         /**
          * Generated
          */
         void setMomentumY(const double& momentumY);
         
         /**
          * Generated
          */
         bool getIsInside() const;
         
         /**
          * Generated
          */
         void setIsInside(const bool& isInside);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         RegularGridCell convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
