#ifndef _TARCH_PARALLEL_MESSAGES_WORKERREQUESTMESSAGE_H
#define _TARCH_PARALLEL_MESSAGES_WORKERREQUESTMESSAGE_H

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>

namespace tarch {
   namespace parallel {
      namespace messages {
         class WorkerRequestMessage;
         class WorkerRequestMessagePacked;
      }
   }
}

/**
 * @author This class was autogenerated by DaStGen
 * 		   DataStructureGenerator (DaStGen), 2007-2009,
 * 		   by Wolfgang Eckhardt
 *
 * 		   build date: 17-10-2010 09:35
 *
 * @date   21/10/2010 09:03
 */
class tarch::parallel::messages::WorkerRequestMessage { 
   
   public:
      
      typedef tarch::parallel::messages::WorkerRequestMessagePacked Packed;
      
      struct PersistentRecords {
         int _tmp;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const int& tmp);
         
         /**
          * Generated
          */
         int getTmp() const;
         
         /**
          * Generated
          */
         void setTmp(const int& tmp);
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      WorkerRequestMessage();
      
      /**
       * Generated
       */
      WorkerRequestMessage(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      WorkerRequestMessage(const int& tmp);
      
      /**
       * Generated
       */
      virtual ~WorkerRequestMessage();
      
      /**
       * Generated
       */
      int getTmp() const;
      
      /**
       * Generated
       */
      void setTmp(const int& tmp);
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      WorkerRequestMessagePacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          */
         static MPI_Datatype Datatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag);
         
         void receive(int source, int tag);
         
         static bool isMessageInQueue(int tag);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 17-10-2010 09:35
    *
    * @date   21/10/2010 09:03
    */
   class tarch::parallel::messages::WorkerRequestMessagePacked { 
      
      public:
         
         struct PersistentRecords {
            int _tmp;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const int& tmp);
            
            /**
             * Generated
             */
            int getTmp() const;
            
            /**
             * Generated
             */
            void setTmp(const int& tmp);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         WorkerRequestMessagePacked();
         
         /**
          * Generated
          */
         WorkerRequestMessagePacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         WorkerRequestMessagePacked(const int& tmp);
         
         /**
          * Generated
          */
         virtual ~WorkerRequestMessagePacked();
         
         /**
          * Generated
          */
         int getTmp() const;
         
         /**
          * Generated
          */
         void setTmp(const int& tmp);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         WorkerRequestMessage convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
