// Copyright (C) 2009 Technische Universitaet Muenchen 
// This file is part of the Peano project. For conditions of distribution and 
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef PEANO_APPLICATIONS_POISSON_JACOBITUTORIAL_RUNNERS_JacobiBatchJobRunner__FOR_REGULAR_GRID_H_
#define PEANO_APPLICATIONS_POISSON_JACOBITUTORIAL_RUNNERS_JacobiBatchJobRunner__FOR_REGULAR_GRID_H_ 


#include "peano/applications/poisson/jacobitutorial/configurations/JacobiBatchJobConfigurationForRegularGrid.h"

namespace peano { 
  namespace applications { 
    namespace poisson { 
      namespace jacobitutorial {
    namespace runners {
      class JacobiBatchJobRunnerForRegularGrid;
    }
    namespace configurations {
      class JacobiBatchJobConfigurationForRegularGrid;
    }
    namespace repositories {
      class JacobiBatchJobRepositoryForRegularGrid;
    }
}
}
}
}



/**
 * Runner for the regular grid.
 *
 * @author Generated by the RaPeP (Peano Rapid Prototyping) tool. 
 */
class peano::applications::poisson::jacobitutorial::runners::JacobiBatchJobRunnerForRegularGrid {
  private:
    int runAsMaster(peano::applications::poisson::jacobitutorial::repositories::JacobiBatchJobRepositoryForRegularGrid& repository);
    
    #ifdef Parallel
    int runAsClient(peano::applications::poisson::jacobitutorial::repositories::JacobiBatchJobRepositoryForRegularGrid& repository);
    #endif
  public:
    JacobiBatchJobRunnerForRegularGrid();
    virtual ~JacobiBatchJobRunnerForRegularGrid();

    /**
     * Executes the run for one configuration.
     * 
     * Whenever the configuration file parser encounters a tag corresponding to
     * a regular grid runner, it tells the corresponding configuration class
     * configurations::peano::applications::poisson::jacobitutorial::configurations::JacobiBatchJobConfigurationForRegularGrid 
     * to create an instance of this class and to parse the configuration file. 
     * If the latter is valid, Peano afterwards calls the runner's run() routine 
     * and passes it the configuration instance. 
     *
     * @param configuration Valid configuration for this experiment run.
     */
    int run(const peano::applications::poisson::jacobitutorial::configurations::JacobiBatchJobConfigurationForRegularGrid& configuration); 
};

#endif
