#ifndef _PEANO_APPLICATIONS_LATTICEBOLTZMANN_BLOCKLATTICEBOLTZMANN_FORCERECORDS_SENDFORCE_H
#define _PEANO_APPLICATIONS_LATTICEBOLTZMANN_BLOCKLATTICEBOLTZMANN_FORCERECORDS_SENDFORCE_H

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>

namespace peano {
   namespace applications {
      namespace latticeboltzmann {
         namespace blocklatticeboltzmann {
            namespace forcerecords {
               class SendForce;
               class SendForcePacked;
            }
         }
      }
   }
}

/**
 * @author This class was autogenerated by DaStGen
 * 		   DataStructureGenerator (DaStGen), 2007-2009,
 * 		   by Wolfgang Eckhardt
 *
 * 		   build date: 09-12-2010 17:47
 *
 * @date   12/05/2011 10:21
 */
class peano::applications::latticeboltzmann::blocklatticeboltzmann::forcerecords::SendForce { 
   
   public:
      
      typedef peano::applications::latticeboltzmann::blocklatticeboltzmann::forcerecords::SendForcePacked Packed;
      
      struct PersistentRecords {
         short int _sendForce;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const short int& sendForce);
         
         /**
          * Generated
          */
         short int getSendForce() const;
         
         /**
          * Generated
          */
         void setSendForce(const short int& sendForce);
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      SendForce();
      
      /**
       * Generated
       */
      SendForce(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      SendForce(const short int& sendForce);
      
      /**
       * Generated
       */
      virtual ~SendForce();
      
      /**
       * Generated
       */
      short int getSendForce() const;
      
      /**
       * Generated
       */
      void setSendForce(const short int& sendForce);
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      SendForcePacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          */
         static MPI_Datatype Datatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag);
         
         void receive(int source, int tag);
         
         static bool isMessageInQueue(int tag);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 09-12-2010 17:47
    *
    * @date   12/05/2011 10:21
    */
   class peano::applications::latticeboltzmann::blocklatticeboltzmann::forcerecords::SendForcePacked { 
      
      public:
         
         struct PersistentRecords {
            short int _sendForce;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const short int& sendForce);
            
            /**
             * Generated
             */
            short int getSendForce() const;
            
            /**
             * Generated
             */
            void setSendForce(const short int& sendForce);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         SendForcePacked();
         
         /**
          * Generated
          */
         SendForcePacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         SendForcePacked(const short int& sendForce);
         
         /**
          * Generated
          */
         virtual ~SendForcePacked();
         
         /**
          * Generated
          */
         short int getSendForce() const;
         
         /**
          * Generated
          */
         void setSendForce(const short int& sendForce);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         SendForce convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
