#ifndef _PEANO_APPLICATIONS_PIC_DEMO_RECORDS_SPACETREEGRIDSTATE_H
#define _PEANO_APPLICATIONS_PIC_DEMO_RECORDS_SPACETREEGRIDSTATE_H

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>
#include "peano/utils/Globals.h"

namespace peano {
   namespace applications {
      namespace pic {
         namespace demo {
            namespace records {
               class SpacetreeGridState;
               class SpacetreeGridStatePacked;
            }
         }
      }
   }
}

#if defined(Parallel)
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 09-12-2010 17:47
    *
    * @date   14/06/2011 15:46
    */
   class peano::applications::pic::demo::records::SpacetreeGridState { 
      
      public:
         
         typedef peano::applications::pic::demo::records::SpacetreeGridStatePacked Packed;
         
         struct PersistentRecords {
            tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
            tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
            double _numberOfInnerVertices;
            double _numberOfBoundaryVertices;
            double _numberOfOuterVertices;
            double _numberOfInnerCells;
            double _numberOfOuterCells;
            int _maxLevel;
            bool _hasRefined;
            bool _hasTriggeredRefinementForNextIteration;
            bool _hasErased;
            bool _hasTriggeredEraseForNextIteration;
            bool _hasChangedVertexOrCellState;
            bool _isTraversalInverted;
            bool _deriveAdjacencyInformation;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
            
            /**
             * Generated
             */
            void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
            
            /**
             * Generated
             */
            void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
            
            /**
             * Generated
             */
            double getNumberOfInnerVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerVertices(const double& numberOfInnerVertices);
            
            /**
             * Generated
             */
            double getNumberOfBoundaryVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
            
            /**
             * Generated
             */
            double getNumberOfOuterVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterVertices(const double& numberOfOuterVertices);
            
            /**
             * Generated
             */
            double getNumberOfInnerCells() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerCells(const double& numberOfInnerCells);
            
            /**
             * Generated
             */
            double getNumberOfOuterCells() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterCells(const double& numberOfOuterCells);
            
            /**
             * Generated
             */
            int getMaxLevel() const;
            
            /**
             * Generated
             */
            void setMaxLevel(const int& maxLevel);
            
            /**
             * Generated
             */
            bool getHasRefined() const;
            
            /**
             * Generated
             */
            void setHasRefined(const bool& hasRefined);
            
            /**
             * Generated
             */
            bool getHasTriggeredRefinementForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
            
            /**
             * Generated
             */
            bool getHasErased() const;
            
            /**
             * Generated
             */
            void setHasErased(const bool& hasErased);
            
            /**
             * Generated
             */
            bool getHasTriggeredEraseForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
            
            /**
             * Generated
             */
            bool getHasChangedVertexOrCellState() const;
            
            /**
             * Generated
             */
            void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
            
            /**
             * Generated
             */
            bool getIsTraversalInverted() const;
            
            /**
             * Generated
             */
            void setIsTraversalInverted(const bool& isTraversalInverted);
            
            /**
             * Generated
             */
            bool getDeriveAdjacencyInformation() const;
            
            /**
             * Generated
             */
            void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         SpacetreeGridState();
         
         /**
          * Generated
          */
         SpacetreeGridState(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         SpacetreeGridState(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
         
         /**
          * Generated
          */
         virtual ~SpacetreeGridState();
         
         /**
          * Generated
          */
         tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
         
         /**
          * Generated
          */
         void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
         
         /**
          * Generated
          */
         double getMinMeshWidth(int elementIndex) const;
         
         /**
          * Generated
          */
         void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
         
         /**
          * Generated
          */
         tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
         
         /**
          * Generated
          */
         void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
         
         /**
          * Generated
          */
         double getMaxMeshWidth(int elementIndex) const;
         
         /**
          * Generated
          */
         void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
         
         /**
          * Generated
          */
         double getNumberOfInnerVertices() const;
         
         /**
          * Generated
          */
         void setNumberOfInnerVertices(const double& numberOfInnerVertices);
         
         /**
          * Generated
          */
         double getNumberOfBoundaryVertices() const;
         
         /**
          * Generated
          */
         void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
         
         /**
          * Generated
          */
         double getNumberOfOuterVertices() const;
         
         /**
          * Generated
          */
         void setNumberOfOuterVertices(const double& numberOfOuterVertices);
         
         /**
          * Generated
          */
         double getNumberOfInnerCells() const;
         
         /**
          * Generated
          */
         void setNumberOfInnerCells(const double& numberOfInnerCells);
         
         /**
          * Generated
          */
         double getNumberOfOuterCells() const;
         
         /**
          * Generated
          */
         void setNumberOfOuterCells(const double& numberOfOuterCells);
         
         /**
          * Generated
          */
         int getMaxLevel() const;
         
         /**
          * Generated
          */
         void setMaxLevel(const int& maxLevel);
         
         /**
          * Generated
          */
         bool getHasRefined() const;
         
         /**
          * Generated
          */
         void setHasRefined(const bool& hasRefined);
         
         /**
          * Generated
          */
         bool getHasTriggeredRefinementForNextIteration() const;
         
         /**
          * Generated
          */
         void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
         
         /**
          * Generated
          */
         bool getHasErased() const;
         
         /**
          * Generated
          */
         void setHasErased(const bool& hasErased);
         
         /**
          * Generated
          */
         bool getHasTriggeredEraseForNextIteration() const;
         
         /**
          * Generated
          */
         void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
         
         /**
          * Generated
          */
         bool getHasChangedVertexOrCellState() const;
         
         /**
          * Generated
          */
         void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
         
         /**
          * Generated
          */
         bool getIsTraversalInverted() const;
         
         /**
          * Generated
          */
         void setIsTraversalInverted(const bool& isTraversalInverted);
         
         /**
          * Generated
          */
         bool getDeriveAdjacencyInformation() const;
         
         /**
          * Generated
          */
         void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         SpacetreeGridStatePacked convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      /**
       * @author This class was autogenerated by DaStGen
       * 		   DataStructureGenerator (DaStGen), 2007-2009,
       * 		   by Wolfgang Eckhardt
       *
       * 		   build date: 09-12-2010 17:47
       *
       * @date   14/06/2011 15:46
       */
      class peano::applications::pic::demo::records::SpacetreeGridStatePacked { 
         
         public:
            
            struct PersistentRecords {
               tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
               tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
               double _numberOfInnerVertices;
               double _numberOfBoundaryVertices;
               double _numberOfOuterVertices;
               double _numberOfInnerCells;
               double _numberOfOuterCells;
               int _maxLevel;
               bool _isTraversalInverted;
               bool _deriveAdjacencyInformation;
               
               /** mapping of records:
               || Member 	|| startbit 	|| length
                |  hasRefined	| startbit 0	| #bits 1
                |  hasTriggeredRefinementForNextIteration	| startbit 1	| #bits 1
                |  hasErased	| startbit 2	| #bits 1
                |  hasTriggeredEraseForNextIteration	| startbit 3	| #bits 1
                |  hasChangedVertexOrCellState	| startbit 4	| #bits 1
                */
               short int _packedRecords0;
               
               /**
                * Generated
                */
               PersistentRecords();
               
               /**
                * Generated
                */
               PersistentRecords(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
               
               /**
                * Generated
                */
               void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
               
               /**
                * Generated
                */
               void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
               
               /**
                * Generated
                */
               double getNumberOfInnerVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerVertices(const double& numberOfInnerVertices);
               
               /**
                * Generated
                */
               double getNumberOfBoundaryVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
               
               /**
                * Generated
                */
               double getNumberOfOuterVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterVertices(const double& numberOfOuterVertices);
               
               /**
                * Generated
                */
               double getNumberOfInnerCells() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerCells(const double& numberOfInnerCells);
               
               /**
                * Generated
                */
               double getNumberOfOuterCells() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterCells(const double& numberOfOuterCells);
               
               /**
                * Generated
                */
               int getMaxLevel() const;
               
               /**
                * Generated
                */
               void setMaxLevel(const int& maxLevel);
               
               /**
                * Generated
                */
               bool getHasRefined() const;
               
               /**
                * Generated
                */
               void setHasRefined(const bool& hasRefined);
               
               /**
                * Generated
                */
               bool getHasTriggeredRefinementForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
               
               /**
                * Generated
                */
               bool getHasErased() const;
               
               /**
                * Generated
                */
               void setHasErased(const bool& hasErased);
               
               /**
                * Generated
                */
               bool getHasTriggeredEraseForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
               
               /**
                * Generated
                */
               bool getHasChangedVertexOrCellState() const;
               
               /**
                * Generated
                */
               void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
               
               /**
                * Generated
                */
               bool getIsTraversalInverted() const;
               
               /**
                * Generated
                */
               void setIsTraversalInverted(const bool& isTraversalInverted);
               
               /**
                * Generated
                */
               bool getDeriveAdjacencyInformation() const;
               
               /**
                * Generated
                */
               void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
               
               
            };
            
         private: 
            PersistentRecords _persistentRecords;
            
         public:
            /**
             * Generated
             */
            SpacetreeGridStatePacked();
            
            /**
             * Generated
             */
            SpacetreeGridStatePacked(const PersistentRecords& persistentRecords);
            
            /**
             * Generated
             */
            SpacetreeGridStatePacked(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted, const bool& deriveAdjacencyInformation);
            
            /**
             * Generated
             */
            virtual ~SpacetreeGridStatePacked();
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
            
            /**
             * Generated
             */
            void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
            
            /**
             * Generated
             */
            double getMinMeshWidth(int elementIndex) const;
            
            /**
             * Generated
             */
            void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
            
            /**
             * Generated
             */
            tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
            
            /**
             * Generated
             */
            void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
            
            /**
             * Generated
             */
            double getMaxMeshWidth(int elementIndex) const;
            
            /**
             * Generated
             */
            void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
            
            /**
             * Generated
             */
            double getNumberOfInnerVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerVertices(const double& numberOfInnerVertices);
            
            /**
             * Generated
             */
            double getNumberOfBoundaryVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
            
            /**
             * Generated
             */
            double getNumberOfOuterVertices() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterVertices(const double& numberOfOuterVertices);
            
            /**
             * Generated
             */
            double getNumberOfInnerCells() const;
            
            /**
             * Generated
             */
            void setNumberOfInnerCells(const double& numberOfInnerCells);
            
            /**
             * Generated
             */
            double getNumberOfOuterCells() const;
            
            /**
             * Generated
             */
            void setNumberOfOuterCells(const double& numberOfOuterCells);
            
            /**
             * Generated
             */
            int getMaxLevel() const;
            
            /**
             * Generated
             */
            void setMaxLevel(const int& maxLevel);
            
            /**
             * Generated
             */
            bool getHasRefined() const;
            
            /**
             * Generated
             */
            void setHasRefined(const bool& hasRefined);
            
            /**
             * Generated
             */
            bool getHasTriggeredRefinementForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
            
            /**
             * Generated
             */
            bool getHasErased() const;
            
            /**
             * Generated
             */
            void setHasErased(const bool& hasErased);
            
            /**
             * Generated
             */
            bool getHasTriggeredEraseForNextIteration() const;
            
            /**
             * Generated
             */
            void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
            
            /**
             * Generated
             */
            bool getHasChangedVertexOrCellState() const;
            
            /**
             * Generated
             */
            void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
            
            /**
             * Generated
             */
            bool getIsTraversalInverted() const;
            
            /**
             * Generated
             */
            void setIsTraversalInverted(const bool& isTraversalInverted);
            
            /**
             * Generated
             */
            bool getDeriveAdjacencyInformation() const;
            
            /**
             * Generated
             */
            void setDeriveAdjacencyInformation(const bool& deriveAdjacencyInformation);
            
            /**
             * Generated
             */
            std::string toString() const;
            
            /**
             * Generated
             */
            void toString(std::ostream& out) const;
            
            
            PersistentRecords getPersistentRecords() const;
            /**
             * Generated
             */
            SpacetreeGridState convert() const;
            
            
         #ifdef Parallel
            protected:
               static tarch::logging::Log _log;
               
               int _senderRank;
               
            public:
               
               /**
                * Global that represents the mpi datatype.
                */
               static MPI_Datatype Datatype;
               
               /**
                * Initializes the data type for the mpi operations. Has to be called
                * before the very first send or receive operation is called.
                */
               static void initDatatype();
               
               static void shutdownDatatype();
               
               void send(int destination, int tag);
               
               void receive(int source, int tag);
               
               static bool isMessageInQueue(int tag);
               
               int getSenderRank() const;
               
         #endif
            
         };
         
         
      #elif !defined(Parallel)
         /**
          * @author This class was autogenerated by DaStGen
          * 		   DataStructureGenerator (DaStGen), 2007-2009,
          * 		   by Wolfgang Eckhardt
          *
          * 		   build date: 09-12-2010 17:47
          *
          * @date   14/06/2011 15:46
          */
         class peano::applications::pic::demo::records::SpacetreeGridState { 
            
            public:
               
               typedef peano::applications::pic::demo::records::SpacetreeGridStatePacked Packed;
               
               struct PersistentRecords {
                  tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
                  tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
                  double _numberOfInnerVertices;
                  double _numberOfBoundaryVertices;
                  double _numberOfOuterVertices;
                  double _numberOfInnerCells;
                  double _numberOfOuterCells;
                  int _maxLevel;
                  bool _hasRefined;
                  bool _hasTriggeredRefinementForNextIteration;
                  bool _hasErased;
                  bool _hasTriggeredEraseForNextIteration;
                  bool _hasChangedVertexOrCellState;
                  bool _isTraversalInverted;
                  /**
                   * Generated
                   */
                  PersistentRecords();
                  
                  /**
                   * Generated
                   */
                  PersistentRecords(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerVertices(const double& numberOfInnerVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfBoundaryVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterVertices(const double& numberOfOuterVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerCells(const double& numberOfInnerCells);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterCells(const double& numberOfOuterCells);
                  
                  /**
                   * Generated
                   */
                  int getMaxLevel() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxLevel(const int& maxLevel);
                  
                  /**
                   * Generated
                   */
                  bool getHasRefined() const;
                  
                  /**
                   * Generated
                   */
                  void setHasRefined(const bool& hasRefined);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredRefinementForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasErased() const;
                  
                  /**
                   * Generated
                   */
                  void setHasErased(const bool& hasErased);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredEraseForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasChangedVertexOrCellState() const;
                  
                  /**
                   * Generated
                   */
                  void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
                  
                  /**
                   * Generated
                   */
                  bool getIsTraversalInverted() const;
                  
                  /**
                   * Generated
                   */
                  void setIsTraversalInverted(const bool& isTraversalInverted);
                  
                  
               };
               
            private: 
               PersistentRecords _persistentRecords;
               
            public:
               /**
                * Generated
                */
               SpacetreeGridState();
               
               /**
                * Generated
                */
               SpacetreeGridState(const PersistentRecords& persistentRecords);
               
               /**
                * Generated
                */
               SpacetreeGridState(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
               
               /**
                * Generated
                */
               virtual ~SpacetreeGridState();
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
               
               /**
                * Generated
                */
               void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
               
               /**
                * Generated
                */
               double getMinMeshWidth(int elementIndex) const;
               
               /**
                * Generated
                */
               void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
               
               /**
                * Generated
                */
               tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
               
               /**
                * Generated
                */
               void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
               
               /**
                * Generated
                */
               double getMaxMeshWidth(int elementIndex) const;
               
               /**
                * Generated
                */
               void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
               
               /**
                * Generated
                */
               double getNumberOfInnerVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerVertices(const double& numberOfInnerVertices);
               
               /**
                * Generated
                */
               double getNumberOfBoundaryVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
               
               /**
                * Generated
                */
               double getNumberOfOuterVertices() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterVertices(const double& numberOfOuterVertices);
               
               /**
                * Generated
                */
               double getNumberOfInnerCells() const;
               
               /**
                * Generated
                */
               void setNumberOfInnerCells(const double& numberOfInnerCells);
               
               /**
                * Generated
                */
               double getNumberOfOuterCells() const;
               
               /**
                * Generated
                */
               void setNumberOfOuterCells(const double& numberOfOuterCells);
               
               /**
                * Generated
                */
               int getMaxLevel() const;
               
               /**
                * Generated
                */
               void setMaxLevel(const int& maxLevel);
               
               /**
                * Generated
                */
               bool getHasRefined() const;
               
               /**
                * Generated
                */
               void setHasRefined(const bool& hasRefined);
               
               /**
                * Generated
                */
               bool getHasTriggeredRefinementForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
               
               /**
                * Generated
                */
               bool getHasErased() const;
               
               /**
                * Generated
                */
               void setHasErased(const bool& hasErased);
               
               /**
                * Generated
                */
               bool getHasTriggeredEraseForNextIteration() const;
               
               /**
                * Generated
                */
               void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
               
               /**
                * Generated
                */
               bool getHasChangedVertexOrCellState() const;
               
               /**
                * Generated
                */
               void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
               
               /**
                * Generated
                */
               bool getIsTraversalInverted() const;
               
               /**
                * Generated
                */
               void setIsTraversalInverted(const bool& isTraversalInverted);
               
               /**
                * Generated
                */
               std::string toString() const;
               
               /**
                * Generated
                */
               void toString(std::ostream& out) const;
               
               
               PersistentRecords getPersistentRecords() const;
               /**
                * Generated
                */
               SpacetreeGridStatePacked convert() const;
               
               
            #ifdef Parallel
               protected:
                  static tarch::logging::Log _log;
                  
                  int _senderRank;
                  
               public:
                  
                  /**
                   * Global that represents the mpi datatype.
                   */
                  static MPI_Datatype Datatype;
                  
                  /**
                   * Initializes the data type for the mpi operations. Has to be called
                   * before the very first send or receive operation is called.
                   */
                  static void initDatatype();
                  
                  static void shutdownDatatype();
                  
                  void send(int destination, int tag);
                  
                  void receive(int source, int tag);
                  
                  static bool isMessageInQueue(int tag);
                  
                  int getSenderRank() const;
                  
            #endif
               
            };
            
            /**
             * @author This class was autogenerated by DaStGen
             * 		   DataStructureGenerator (DaStGen), 2007-2009,
             * 		   by Wolfgang Eckhardt
             *
             * 		   build date: 09-12-2010 17:47
             *
             * @date   14/06/2011 15:46
             */
            class peano::applications::pic::demo::records::SpacetreeGridStatePacked { 
               
               public:
                  
                  struct PersistentRecords {
                     tarch::la::Vector<DIMENSIONS,double> _minMeshWidth;
                     tarch::la::Vector<DIMENSIONS,double> _maxMeshWidth;
                     double _numberOfInnerVertices;
                     double _numberOfBoundaryVertices;
                     double _numberOfOuterVertices;
                     double _numberOfInnerCells;
                     double _numberOfOuterCells;
                     int _maxLevel;
                     bool _isTraversalInverted;
                     
                     /** mapping of records:
                     || Member 	|| startbit 	|| length
                      |  hasRefined	| startbit 0	| #bits 1
                      |  hasTriggeredRefinementForNextIteration	| startbit 1	| #bits 1
                      |  hasErased	| startbit 2	| #bits 1
                      |  hasTriggeredEraseForNextIteration	| startbit 3	| #bits 1
                      |  hasChangedVertexOrCellState	| startbit 4	| #bits 1
                      */
                     short int _packedRecords0;
                     
                     /**
                      * Generated
                      */
                     PersistentRecords();
                     
                     /**
                      * Generated
                      */
                     PersistentRecords(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
                     
                     /**
                      * Generated
                      */
                     tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
                     
                     /**
                      * Generated
                      */
                     void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
                     
                     /**
                      * Generated
                      */
                     tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
                     
                     /**
                      * Generated
                      */
                     void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfInnerVertices() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfInnerVertices(const double& numberOfInnerVertices);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfBoundaryVertices() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfOuterVertices() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfOuterVertices(const double& numberOfOuterVertices);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfInnerCells() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfInnerCells(const double& numberOfInnerCells);
                     
                     /**
                      * Generated
                      */
                     double getNumberOfOuterCells() const;
                     
                     /**
                      * Generated
                      */
                     void setNumberOfOuterCells(const double& numberOfOuterCells);
                     
                     /**
                      * Generated
                      */
                     int getMaxLevel() const;
                     
                     /**
                      * Generated
                      */
                     void setMaxLevel(const int& maxLevel);
                     
                     /**
                      * Generated
                      */
                     bool getHasRefined() const;
                     
                     /**
                      * Generated
                      */
                     void setHasRefined(const bool& hasRefined);
                     
                     /**
                      * Generated
                      */
                     bool getHasTriggeredRefinementForNextIteration() const;
                     
                     /**
                      * Generated
                      */
                     void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
                     
                     /**
                      * Generated
                      */
                     bool getHasErased() const;
                     
                     /**
                      * Generated
                      */
                     void setHasErased(const bool& hasErased);
                     
                     /**
                      * Generated
                      */
                     bool getHasTriggeredEraseForNextIteration() const;
                     
                     /**
                      * Generated
                      */
                     void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
                     
                     /**
                      * Generated
                      */
                     bool getHasChangedVertexOrCellState() const;
                     
                     /**
                      * Generated
                      */
                     void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
                     
                     /**
                      * Generated
                      */
                     bool getIsTraversalInverted() const;
                     
                     /**
                      * Generated
                      */
                     void setIsTraversalInverted(const bool& isTraversalInverted);
                     
                     
                  };
                  
               private: 
                  PersistentRecords _persistentRecords;
                  
               public:
                  /**
                   * Generated
                   */
                  SpacetreeGridStatePacked();
                  
                  /**
                   * Generated
                   */
                  SpacetreeGridStatePacked(const PersistentRecords& persistentRecords);
                  
                  /**
                   * Generated
                   */
                  SpacetreeGridStatePacked(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth, const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth, const double& numberOfInnerVertices, const double& numberOfBoundaryVertices, const double& numberOfOuterVertices, const double& numberOfInnerCells, const double& numberOfOuterCells, const int& maxLevel, const bool& hasRefined, const bool& hasTriggeredRefinementForNextIteration, const bool& hasErased, const bool& hasTriggeredEraseForNextIteration, const bool& hasChangedVertexOrCellState, const bool& isTraversalInverted);
                  
                  /**
                   * Generated
                   */
                  virtual ~SpacetreeGridStatePacked();
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMinMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMinMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& minMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getMinMeshWidth(int elementIndex) const;
                  
                  /**
                   * Generated
                   */
                  void setMinMeshWidth(int elementIndex, const double& minMeshWidth);
                  
                  /**
                   * Generated
                   */
                  tarch::la::Vector<DIMENSIONS,double> getMaxMeshWidth() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxMeshWidth(const tarch::la::Vector<DIMENSIONS,double>& maxMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getMaxMeshWidth(int elementIndex) const;
                  
                  /**
                   * Generated
                   */
                  void setMaxMeshWidth(int elementIndex, const double& maxMeshWidth);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerVertices(const double& numberOfInnerVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfBoundaryVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfBoundaryVertices(const double& numberOfBoundaryVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterVertices() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterVertices(const double& numberOfOuterVertices);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfInnerCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfInnerCells(const double& numberOfInnerCells);
                  
                  /**
                   * Generated
                   */
                  double getNumberOfOuterCells() const;
                  
                  /**
                   * Generated
                   */
                  void setNumberOfOuterCells(const double& numberOfOuterCells);
                  
                  /**
                   * Generated
                   */
                  int getMaxLevel() const;
                  
                  /**
                   * Generated
                   */
                  void setMaxLevel(const int& maxLevel);
                  
                  /**
                   * Generated
                   */
                  bool getHasRefined() const;
                  
                  /**
                   * Generated
                   */
                  void setHasRefined(const bool& hasRefined);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredRefinementForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredRefinementForNextIteration(const bool& hasTriggeredRefinementForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasErased() const;
                  
                  /**
                   * Generated
                   */
                  void setHasErased(const bool& hasErased);
                  
                  /**
                   * Generated
                   */
                  bool getHasTriggeredEraseForNextIteration() const;
                  
                  /**
                   * Generated
                   */
                  void setHasTriggeredEraseForNextIteration(const bool& hasTriggeredEraseForNextIteration);
                  
                  /**
                   * Generated
                   */
                  bool getHasChangedVertexOrCellState() const;
                  
                  /**
                   * Generated
                   */
                  void setHasChangedVertexOrCellState(const bool& hasChangedVertexOrCellState);
                  
                  /**
                   * Generated
                   */
                  bool getIsTraversalInverted() const;
                  
                  /**
                   * Generated
                   */
                  void setIsTraversalInverted(const bool& isTraversalInverted);
                  
                  /**
                   * Generated
                   */
                  std::string toString() const;
                  
                  /**
                   * Generated
                   */
                  void toString(std::ostream& out) const;
                  
                  
                  PersistentRecords getPersistentRecords() const;
                  /**
                   * Generated
                   */
                  SpacetreeGridState convert() const;
                  
                  
               #ifdef Parallel
                  protected:
                     static tarch::logging::Log _log;
                     
                     int _senderRank;
                     
                  public:
                     
                     /**
                      * Global that represents the mpi datatype.
                      */
                     static MPI_Datatype Datatype;
                     
                     /**
                      * Initializes the data type for the mpi operations. Has to be called
                      * before the very first send or receive operation is called.
                      */
                     static void initDatatype();
                     
                     static void shutdownDatatype();
                     
                     void send(int destination, int tag);
                     
                     void receive(int source, int tag);
                     
                     static bool isMessageInQueue(int tag);
                     
                     int getSenderRank() const;
                     
               #endif
                  
               };
               
               
            
         #endif
         
         #endif
         
