// Copyright (C) 2009 Technische Universitaet Muenchen 
// This file is part of the Peano project. For conditions of distribution and 
// use, please see the copyright notice at www5.in.tum.de/peano
#ifndef PEANO_APPLICATIONS_SHALLOWWATER_RUNNERS_ShallowWaterBatchJobRunner__FOR_REGULAR_GRID_H_
#define PEANO_APPLICATIONS_SHALLOWWATER_RUNNERS_ShallowWaterBatchJobRunner__FOR_REGULAR_GRID_H_


#include "peano/applications/shallowwater/configurations/ShallowWaterBatchJobConfigurationForRegularGrid.h"

namespace peano { 
  namespace applications { 
    namespace shallowwater {
    namespace runners {
      class ShallowWaterBatchJobRunnerForRegularGrid;
    }
    namespace configurations {
      class ShallowWaterBatchJobConfigurationForRegularGrid;
    }
    namespace repositories {
      class ShallowWaterBatchJobRepositoryForRegularGrid;
    }
}
}
}



/**
 * Runner for the regular grid.
 *
 * @author Generated by the RaPeP (Peano Rapid Prototyping) tool. 
 */
class peano::applications::shallowwater::runners::ShallowWaterBatchJobRunnerForRegularGrid {
  private:
    int runAsMaster(peano::applications::shallowwater::repositories::ShallowWaterBatchJobRepositoryForRegularGrid& repository);
    
    #ifdef Parallel
    int runAsClient(peano::applications::shallowwater::repositories::ShallowWaterBatchJobRepositoryForRegularGrid& repository);
    #endif
  public:
    ShallowWaterBatchJobRunnerForRegularGrid();
    virtual ~ShallowWaterBatchJobRunnerForRegularGrid();

    /**
     * Executes the run for one configuration.
     * 
     * Whenever the configuration file parser encounters a tag corresponding to
     * a regular grid runner, it tells the corresponding configuration class
     * configurations::peano::applications::shallowwater::configurations::ShallowWaterBatchJobConfigurationForRegularGrid 
     * to create an instance of this class and to parse the configuration file. 
     * If the latter is valid, Peano afterwards calls the runner's run() routine 
     * and passes it the configuration instance. 
     *
     * @param configuration Valid configuration for this experiment run.
     */
    int run(const peano::applications::shallowwater::configurations::ShallowWaterBatchJobConfigurationForRegularGrid& configuration); 
};

#endif
